inst_Items = {
{ item_instance = "yfauun_itar_oldcamp_l", friendly_name = "Одежда тени"},
{ item_instance = "yfauun_itar_oldcamp_m", friendly_name = "Доспехи призрака"},
{ item_instance = "yfauun_itar_oldcamp_h", friendly_name = "Доспехи лидера призраков"},
{ item_instance = "yfauun_itar_oldcampg_l", friendly_name = "Легкие доспехи стражника"},
{ item_instance = "yfauun_itar_oldcampg_m", friendly_name = "Средние доспехи стражника"},
{ item_instance = "yfauun_grd_armor_h", friendly_name = "Тяжелые доспехи стражника"},
{ item_instance = "yfauun_itar_croissant2", friendly_name = "Одежда банкира"},
{ item_instance = "yfauun_itar_newcamp_l", friendly_name = "Одежда Вора"},
{ item_instance = "yfauun_org_newcamp_m", friendly_name = "Средние доспехи вора"},
{ item_instance = "yfauun_org_newcamp_h", friendly_name = "Тяжелые доспехи вора"},
{ item_instance = "yfauun_itar_newcampm_l", friendly_name = "Легкие доспехи наемника"},
{ item_instance = "yfauun_itar_newcampm_m", friendly_name = "Средние доспехи наемника"},
{ item_instance = "yfauun_org_newcampm_h", friendly_name = "Тяжелые доспехи наемника"},
{ item_instance = "yfauun_org_newcampm_hg", friendly_name = "Тяжелые доспехи генерала"},
{ item_instance = "yfauun_itar_orc_warrior", friendly_name = "Доспехи воина орков"},
{ item_instance = "yfauun_itar_orc_hscout", friendly_name = "Средние доспехи орков"},
{ item_instance = "yfauun_itar_orc_elite", friendly_name = "Доспехи элитного воина орков"},
{ item_instance = "yfauun_itar_orc_shaman", friendly_name = "Облачение орка-шамана"},
{ item_instance = "yfauun_itar_orc_hshaman", friendly_name = "Облачение верховного орка-шамана"},
{ item_instance = "yfauun_itar_orc_templar", friendly_name = "Cредние доспехи орков"},
{ item_instance = "yfauun_itsh_shield_01", friendly_name = "Деревянный щит"},
{ item_instance = "yfauun_itsh_shield_02", friendly_name = "Круглый щит"},
{ item_instance = "yfauun_itsh_shield_03", friendly_name = "Железный щит"},
{ item_instance = "yfauun_itsh_shield_04", friendly_name = "Костяной щит"},
{ item_instance = "yfauun_itar_nov_l", friendly_name = "Роба послушника"},
{ item_instance = "yfauun_itar_kdf_l", friendly_name = "Мантия мага огня"},
{ item_instance = "yfauun_itar_kdf_h", friendly_name = "Тяжелая мантия магов огня"},
{ item_instance = "yfauun_itar_xardas", friendly_name = "Мантия черной магии"},
{ item_instance = "yfauun_itar_dementor", friendly_name = "Мантия тьмы"},
{ item_instance = "yfauun_itar_kdw_h", friendly_name = "Тяжелая мантия магов воды"},
{ item_instance = "yfauun_itar_kdw_l_addon", friendly_name = "Мантия магов воды"},
{ item_instance = "yfauun_itar_fire_hh", friendly_name = "Тяжелая огненная мантия с капюшоном"},
{ item_instance = "yfauun_itar_fire_mh", friendly_name = "Мантия высших магов огня с капюшоном"},
{ item_instance = "yfauun_itar_necr_mh", friendly_name = "Мантия темного мага с капюшоном"},
{ item_instance = "yfauun_itar_fire_lh", friendly_name = "Мантия мага огня с капюшоном"},
{ item_instance = "yfauun_itar_water_lh", friendly_name = "Облачение магов воды с капюшоном"},
{ item_instance = "yfauun_itar_torba", friendly_name = "Сумка"},
{ item_instance = "yfauun_itar_torba2", friendly_name = "Сумка1"},
{ item_instance = "yfauun_itar_torba3", friendly_name = "Сумка2"},
{ item_instance = "yfauun_itar_koszyk", friendly_name = "Корзинка для зерна"},
{ item_instance = "yfauun_itar_koszyk2", friendly_name = "Корзинка для руды"}, 
{ item_instance = "yfauun_itar_koszyk3", friendly_name = "Корзинка для травы"},
{ item_instance = "yfauun_itar_judge", friendly_name = "Мантия судьи"},
{ item_instance = "yfauun_itar_governor", friendly_name = "Богатая красная одежда горожанина"},
{ item_instance = "yfauun_itar_smith", friendly_name = "Одежда кузнеца"},
{ item_instance = "yfauun_itar_barkeeper", friendly_name = "Одежда трактирщика"},
{ item_instance = "yfauun_itar_vlk_l", friendly_name = "Коричневый дублет"},
{ item_instance = "yfauun_itar_vlk_m", friendly_name = "Розовый стеганый дублет"},
{ item_instance = "yfauun_itar_vlk_h", friendly_name = "Бежевый дублет"},
{ item_instance = "yfauun_itar_vlkbabe_l2", friendly_name = "Голубое платье"},
{ item_instance = "yfauun_itar_vlkbabe_m", friendly_name = "Белое платье"},
{ item_instance = "yfauun_itar_vlkbabe_h", friendly_name = "Черное платье"},
{ item_instance = "yfauun_itar_bau_l", friendly_name = "Простая фермерская одежда"},
{ item_instance = "yfauun_itar_bau_m", friendly_name = "Добротная крестьянская одежда"},
{ item_instance = "yfauun_itar_baubabe_l", friendly_name = "Бежевое платье"},
{ item_instance = "yfauun_itar_baubabe_m", friendly_name = "Зеленое платье"},
{ item_instance = "yfauun_itar_baubabe_n", friendly_name = "Сиреневое платье"},
{ item_instance = "yfauun_itar_leather_l", friendly_name = "Кожаные доспехи"},
{ item_instance = "yfauun_itar_prisoner", friendly_name = "Штаны рудокопа"},
{ item_instance = "yfauun_itar_vlk_khr01", friendly_name = "Короткий дублет"},
{ item_instance = "yfauun_itar_vlk_d", friendly_name = "Синий дублет"},
{ item_instance = "yfauun_itar_vlk_j", friendly_name = "Стеганый дублет"},
{ item_instance = "yfauun_itar_vlk_z", friendly_name = "Бежевый стеганый дублет"},
{ item_instance = "yfauun_itar_vlk_a", friendly_name = "Серый стеганый дублет"},
{ item_instance = "yfauun_itar_vlk_c", friendly_name = "Темно-зеленый стеганый дублет"},
{ item_instance = "yfauun_itar_vlk_y", friendly_name = "Черный дублет"},
{ item_instance = "yfauun_itar_vlk_f", friendly_name = "Белый плащ"},
{ item_instance = "yfauun_itar_vlk_e", friendly_name = "Бежевый плащ"},
{ item_instance = "yfauun_itar_vlk_p", friendly_name = "Коричневый плащ"},
{ item_instance = "yfauun_itar_vlk_n", friendly_name = "Черный плащ"},
{ item_instance = "yfauun_itar_vlk_q", friendly_name = "Желтый дублет"},
{ item_instance = "yfauun_itar_vlk_w", friendly_name = "Серый дублет"},
{ item_instance = "yfauun_itar_vlk_y1", friendly_name = "Красный дублет"},
{ item_instance = "yfauun_itar_bau_c", friendly_name = "Одежда фермера 1"},
{ item_instance = "yfauun_itar_bau_a", friendly_name = "Одежда фермера 2"},
{ item_instance = "yfauun_itar_bau_b", friendly_name = "Одежда фермера 3"},
{ item_instance = "yfauun_itar_burg4", friendly_name = "Хорошая одежда горожанина"},
{ item_instance = "yfauun_itar_woodcutter", friendly_name = "Одежда лесоруба"},
{ item_instance = "yfauun_itar_vlkbabe_l", friendly_name = "Голубое платье"},
{ item_instance = "yfauun_itar_vlkbabe_m2", friendly_name = "Белое платье"},
{ item_instance = "yfauun_itar_vlkbabe_h2", friendly_name = "Черное платье"},
{ item_instance = "yfauun_itar_vlkbabe_l2", friendly_name = "Бежевое платье"},
{ item_instance = "yfauun_itar_baubabe_m2", friendly_name = "Зеленое платье"},
{ item_instance = "yfauun_itar_vlkbabe_s", friendly_name = "Красное платье"},
{ item_instance = "yfauun_itar_newplat_01", friendly_name = "Дворянское голубое платье"},
{ item_instance = "yfauun_itar_newplat_02", friendly_name = "Дворянское красное платье"},
{ item_instance = "yfauun_itar_newplat_03", friendly_name = "Дворянское зеленое платье"},
{ item_instance = "yfauun_itar_newplat_04", friendly_name = "Дворянское черное платье"},
{ item_instance = "yfauun_itar_newplat_05", friendly_name = "Дорогое красное платье"},
{ item_instance = "yfauun_itar_stani", friendly_name = "Штаны моряка"},
{ item_instance = "yfauun_itar_slave", friendly_name = "Одежда нищеброда"},
{ item_instance = "yfauun_itar_sailor", friendly_name = "Простая одежда1"},
{ item_instance = "yfauun_itar_sailor1", friendly_name = "Простая одежда2"},
{ item_instance = "yfauun_itar_sailor2", friendly_name = "Простая одежда3"},
{ item_instance = "yfauun_itar_sailor3", friendly_name = "Простая одежда4"},
{ item_instance = "yfauun_itar_mil_m", friendly_name = "Средние доспехи ополчения"},
{ item_instance = "yfauun_itar_sld_l_g2", friendly_name = "Легкие доспехи наемника"},
{ item_instance = "yfauun_itar_pal_skel", friendly_name = "Старые рыцарские доспехи"},
{ item_instance = "yfauun_itar_mayazombie_addon", friendly_name = "Старые доспехи"},
{ item_instance = "yfauun_itar_bdt_h", friendly_name = "Тяжелая одежда из шкур с шарфом"},
{ item_instance = "yfauun_itar_fknght", friendly_name = "Броня вольного рыцаря"},
{ item_instance = "yfauun_itar_col", friendly_name = "Доспехи колониста"},
{ item_instance = "yfauun_itar_stranger", friendly_name = "Легкие доспехи охотников на орков"},
{ item_instance = "yfauun_itar_orcmerc_m", friendly_name = "Средние доспехи наемника орков"},
{ item_instance = "yfauun_itar_larm_m", friendly_name = "Средняя кожаная броня"},
{ item_instance = "yfauun_itar_hrb_h", friendly_name = "Тяжелая кольчуга"},
{ item_instance = "yfauun_itar_pir_m_addon", friendly_name = "Доспехи пирата"},
{ item_instance = "yfauun_itar_chl_m", friendly_name = "Кольчужно-кожаные доспехи"},
{ item_instance = "yfauun_itar_crawler_l", friendly_name = "Легкие доспехи из панцирных пластин"},
{ item_instance = "yfauun_itar_neutralm", friendly_name = "Доспехи убийцы"},
{ item_instance = "yfauun_itar_hunter4", friendly_name = "Добротные доспехи охотника"},
{ item_instance = "yfauun_itar_mil_l", friendly_name = "Легкие доспехи ополчения"},
{ item_instance = "yfauun_itar_bdt_m", friendly_name = "Одежда из шкур с шарфом"},
{ item_instance = "yfauun_itar_albino", friendly_name = "Доспехи альбиноса"},
{ item_instance = "yfauun_itar_ranger_h", friendly_name = "Кольчуга с кожаной курткой"},
{ item_instance = "yfauun_itar_hnt_l", friendly_name = "Легкая охотничья одежда"},
{ item_instance = "yfauun_itar_orcmerc_l", friendly_name = "Легкий доспех наемника орков"},
{ item_instance = "yfauun_itar_ghrb", friendly_name = "Серая кольчуга"},
{ item_instance = "yfauun_itar_pir_l_addon", friendly_name = "Одежда пирата"},
{ item_instance = "yfauun_itar_vav", friendly_name = "Походное облачение"},
{ item_instance = "yfauun_itar_walker", friendly_name = "Облачение путешественника"},
{ item_instance = "yfauun_itar_darkrobe", friendly_name = "Темная роба"},
{ item_instance = "yfauun_itar_kdw_p", friendly_name = "Походная мантия мага воды"},
{ item_instance = "yfauun_itar_kdw_l", friendly_name = "Мантия ученика мага воды"},
{ item_instance = "yfauun_itar_babe_leather_l", friendly_name = "Кожаный доспех (жен)"},
{ item_instance = "yfauun_itar_pir_m_horinis", friendly_name = "Одежда моряка"},
{ item_instance = "yfauun_itar_pir_m_horinis2", friendly_name = "Одежда авантюриста"},
{ item_instance = "yfauun_itar_neutral", friendly_name = "Одежда охотника"},
{ item_instance = "yfauun_itar_croissant", friendly_name = "Одеяние переговорщика"},
{ item_instance = "yfauun_itar_chainmail", friendly_name = "Легкая кольчуга"},
{ item_instance = "yfauun_itar_traveler", friendly_name = "Облачение путешественника"},
{ item_instance = "yfauun_itar_hunter3", friendly_name = "Изношенная одежда охотника"},
{ item_instance = "yfauun_itar_mil_h", friendly_name = "Броня капитана ополчения"},
{ item_instance = "yfauun_itar_pal_m", friendly_name = "Доспехи рыцаря"},
{ item_instance = "yfauun_itar_sld_h_g2", friendly_name = "Тяжелые доспехи наемника"},
{ item_instance = "yfauun_itar_sld_m_g2", friendly_name = "Средние доспехи наемника"},
{ item_instance = "yfauun_itar_djg_crawler", friendly_name = "Доспехи из панцирей краулеров"},
{ item_instance = "yfauun_itar_djg_l", friendly_name = "Легкие доспехи охотника на драконов"},
{ item_instance = "yfauun_itar_djg_m", friendly_name = "Средние доспехи охотника на драконов"},
{ item_instance = "yfauun_itar_raven_addon", friendly_name = "Доспехи Ворона"},
{ item_instance = "yfauun_itar_champion", friendly_name = "Броня чемпиона"},
{ item_instance = "yfauun_itar_knggrd", friendly_name = "Доспехи королевского гвардейца"},
{ item_instance = "yfauun_itar_kllr_h", friendly_name = "Тяжелые доспехи убийцы"},
{ item_instance = "yfauun_itar_dh_h", friendly_name = "Средние доспехи охотника на орков"},
{ item_instance = "yfauun_itar_sct_h", friendly_name = "Тяжелые солдатские доспехи разведчика"},
{ item_instance = "yfauun_itar_pir_h_addon", friendly_name = "Одежда капитана"},
{ item_instance = "yfauun_itar_chl_h", friendly_name = "Тяжелые кольчужно-кожаные доспехи"},
{ item_instance = "yfauun_itar_orchunterh", friendly_name = "Тяжелые доспехи охотников на орков"},
{ item_instance = "yfauun_itar_pal_h", friendly_name = "Доспехи паладина"},
{ item_instance = "yfauun_itar_djg_h", friendly_name = "Тяжелые доспехи охотника на драконов"},
{ item_instance = "yfauun_itar_kng_h", friendly_name = "Доспехи короля"},
{ item_instance = "yfauun_itar_magie_h", friendly_name = "Древние рудные доспехи"},
{ item_instance = "yfauun_itar_stlarm", friendly_name = "Стальные латы"},
{ item_instance = "zdpwla_itfo_wineberrys", friendly_name = "Виноградная гроздь"},
{ item_instance = "zdpwla_itfo_wineberrys2", friendly_name = "Дикая виноградная гроздь"},
{ item_instance = "zdpwla_itfo_rice", friendly_name = "Рис"},
{ item_instance = "zdpwla_itfo_soup", friendly_name = "Суп из кореньев"},
{ item_instance = "zdpwla_itfo_meatbugragout", friendly_name = "Рагу из жуков"},
{ item_instance = "zdpwla_itfo_crawlersoup", friendly_name = "Суп с мясом ползунов"},
{ item_instance = "zdpwla_itfo_bottleofbeer", friendly_name = "Бутылка пива"},
{ item_instance = "zdpwla_itfo_ricebooze", friendly_name = "Рисовый шнапс"},
{ item_instance = "zdpwla_itfo_plants_berrys_01", friendly_name = "Лесная ягода"},
{ item_instance = "zdpwla_itfo_plants_flameberry_01", friendly_name = "Огненная ягода"},
{ item_instance = "zdpwla_itfo_plants_seraphis_01", friendly_name = "Серафис"},
{ item_instance = "zdpwla_itfo_plants_velayis_01", friendly_name = "Велейс"},
{ item_instance = "zdpwla_itfo_plants_mountainmoss_01", friendly_name = "Горный мох"},
{ item_instance = "zdpwla_itfo_plants_mountainmoss_02", friendly_name = "Могильный мох"},
{ item_instance = "zdpwla_itfo_plants_nightshadow_01", friendly_name = "Солнечник"},	
{ item_instance = "zdpwla_itfo_plants_nightshadow_02", friendly_name = "Лунник"},
{ item_instance = "zdpwla_itfo_plants_orcherb_01", friendly_name = "Орочий лист"},
{ item_instance = "zdpwla_itfo_plants_orcherb_02", friendly_name = "Дубовый лист"},
{ item_instance = "zdpwla_itfo_plants_bloodwood_01", friendly_name = "Семена бука"},
{ item_instance = "zdpwla_itfo_plants_towerwood_01", friendly_name = "Желуди"},
{ item_instance = "zdpwla_itfo_plants_ravenherb_01", friendly_name = "Воронья трава"},
{ item_instance = "zdpwla_itfo_plants_ravenherb_02", friendly_name = "Темные травы"},
{ item_instance = "zdpwla_itfo_plants_stoneroot_01", friendly_name = "Каменный корень"},
{ item_instance = "zdpwla_itfo_plants_stoneroot_02", friendly_name = "Драконья трава"},
{ item_instance = "zdpwla_itfo_plants_trollberrys_01", friendly_name = "Вишня троллей"},
{ item_instance = "itmi_spices", friendly_name = "Специи"},
{ item_instance = "zdpwla_itfo_apple", friendly_name = "Яблоко"},
{ item_instance = "zdpwla_itfo_cheese", friendly_name = "Сыр"},
{ item_instance = "zdpwla_itfo_bacon", friendly_name = "Окорок"},
{ item_instance = "zdpwla_itfo_bread", friendly_name = "Хлеб"},
{ item_instance = "zdpwla_itfo_fish", friendly_name = "Рыба"},
{ item_instance = "zdpwla_itfomuttonraw", friendly_name = "Сырое мясо"},
{ item_instance = "zdpwla_itfomutton", friendly_name = "Жареное мясо"},
{ item_instance = "zdpwla_itfo_stew", friendly_name = "Похлебка"},
{ item_instance = "zdpwla_itfo_xpstew", friendly_name = "Похлебка теклы"},
{ item_instance = "zdpwla_itfo_fishsoup", friendly_name = "Уха"},
{ item_instance = "zdpwla_itfo_sausage", friendly_name = "Колбаса"},
{ item_instance = "zdpwla_itfo_honey", friendly_name = "Мед"},
{ item_instance = "zdpwla_itfo_water", friendly_name = "Вода"},
{ item_instance = "zdpwla_itfo_beer", friendly_name = "Пиво"},
{ item_instance = "zdpwla_itfo_booze", friendly_name = "Джин"},
{ item_instance = "zdpwla_itfo_wine", friendly_name = "Вино"},
{ item_instance = "zdpwla_itfo_milk", friendly_name = "Молоко"},
{ item_instance = "zdpwla_itfo_addon_shellflesh", friendly_name = "Мясо моллюска"},
{ item_instance = "zdpwla_itfo_addon_rum", friendly_name = "Ром"},
{ item_instance = "zdpwla_itfo_addon_grog", friendly_name = "Грог"},
{ item_instance = "zdpwla_itfo_addon_loushammer", friendly_name = "Молот Лу"},
{ item_instance = "zdpwla_itfo_addon_schlafhammer", friendly_name = "Двойной молот"},
{ item_instance = "zdpwla_itfo_addon_schnellerhering", friendly_name = "Быстрая селедка"},
{ item_instance = "zdpwla_itfo_addon_pfeffer_01", friendly_name = "Мешочек с перцем"},
{ item_instance = "zdpwla_itfo_addon_firestew", friendly_name = "Пламенная нарезка"},
{ item_instance = "zdpwla_itfo_addon_meatsoup", friendly_name = "Мясная похлебка"},
{ item_instance = "zdpwla_itfo_addon_meatsoup", friendly_name = "Мясная похлебка"},
{ item_instance = "zdpwla_itfo_monk_wine", friendly_name = "Монастырское вино"},
{ item_instance = "zdpwla_itfo_pie", friendly_name = "Пирожок"},
{ item_instance = "zdpwla_itfo_goatleg", friendly_name = "Жареная нога"},
{ item_instance = "zdpwla_itfo_goatmilk", friendly_name = "Ведро молока"},
{ item_instance = "zdpwla_itfo_barbecue", friendly_name = "Шашлык"},
{ item_instance = "zdpwla_itfo_cake", friendly_name = "Сладкий рулет"},
{ item_instance = "zdpwla_itfo_tea", friendly_name = "Чай"},
{ item_instance = "zdpwla_itfo_fishfry", friendly_name = "Жареная рыба"},
{ item_instance = "zdpwla_itfo_shaurma", friendly_name = "Шаурма"},
{ item_instance = "zdpwla_itfo_flour", friendly_name = "Мешок муки"},
{ item_instance = "zdpwla_itfo_rice_grain", friendly_name = "Рисовое зерно"},
{ item_instance = "zdpwla_itfo_crl_meat", friendly_name = "Мясо ползуна"},
{ item_instance = "zdpwla_itfo_barley", friendly_name = "Ячмень"},
{ item_instance = "zdpwla_itfo_hmel", friendly_name = "Хмель"}, 
{ item_instance = "zdpwla_itfo_millet", friendly_name = "Пшено"}, 
{ item_instance = "zdpwla_itfo_cane", friendly_name = "Тростник"}, 
{ item_instance = "zdpwla_itfo_fish_pie", friendly_name = "Рыбный пирожок"},
{ item_instance = "zdpwla_itfo_apple_pie", friendly_name = "Яблочный пирожок"},
{ item_instance = "zdpwla_itfo_berry_pie", friendly_name = "Ягодный пирожок"},
{ item_instance = "zdpwla_itfo_egg", friendly_name = "Яйцо"},
{ item_instance = "zdpwla_itfo_mors", friendly_name = "Морс"},
{ item_instance = "zdpwla_itfo_samogon", friendly_name = "Самогон"},
{ item_instance = "zdpwla_itfo_applepie", friendly_name = "Яблочный пирог"},
{ item_instance = "zdpwla_itfo_medovuha", friendly_name = "Медовуха"},
{ item_instance = "zdpwla_itfo_beafpie", friendly_name = "Пирог со шкварками"},
{ item_instance = "zdpwla_itfo_fishpie", friendly_name = "Рыбный пирог"},
{ item_instance = "zdpwla_itfo_blinchik", friendly_name = "Блинчик"},
{ item_instance = "zdpwla_itfo_mblinchik", friendly_name = "Блинчик с медом"},
{ item_instance = "zdpwla_itfo_fishfried", friendly_name = "Жареная рыба1"},
{ item_instance = "ooltyb_itfo_meatbugfried", friendly_name = "Жареный жук"},
{ item_instance = "zdpwla_itfo_poorsoup", friendly_name = "Суп бедняка"},
{ item_instance = "zdpwla_itfo_mushroomoffal", friendly_name = "Грибная требуха"},
{ item_instance = "zdpwla_itfo_marinmushroom", friendly_name = "Маринованные грибы"},
{ item_instance = "zdpwla_itfo_fishbatter", friendly_name = "Рыба в кляре"},
{ item_instance = "zdpwla_itfo_berrysalad", friendly_name = "Ягодный салат"},
{ item_instance = "zdpwla_itfo_acornbooze", friendly_name = "Желудевка"},
{ item_instance = "zdpwla_itfo_mushroomcutlet", friendly_name = "Грибная котлета"},
{ item_instance = "zdpwla_itfo_grapejuice", friendly_name = "Виноградный сок"},
{ item_instance = "zdpwla_itfo_honeymeat", friendly_name = "Мясо в медовом соусе"},
{ item_instance = "zdpwla_itfo_meatbugpate", friendly_name = "Паштет из жуков"},
{ item_instance = "zdpwla_itfo_acornbread", friendly_name = "Желудевый хлеб"},
{ item_instance = "zdpwla_itfo_berryliqueur", friendly_name = "Ягодная наливка"},
{ item_instance = "zdpwla_itfo_seasalad", friendly_name = "Морской салат"},
{ item_instance = "zdpwla_itfo_bomber", friendly_name = "Бомбер"},
{ item_instance = "zdpwla_itfo_casserole", friendly_name = "Фермерская запеканка"},
{ item_instance = "zdpwla_itfo_winestew", friendly_name = "Тушеное мясо в вине"},
{ item_instance = "zdpwla_itfo_friedegg", friendly_name = "Яичница с колбасой"},
{ item_instance = "zdpwla_itfo_smokedfish", friendly_name = "Копченая рыба"},
{ item_instance = "zdpwla_itfo_honeybiscuit", friendly_name = "Медовое печенье"},
{ item_instance = "zdpwla_itfo_berrypie", friendly_name = "Ягодный пирог"},
{ item_instance = "zdpwla_itfo_magicsoup", friendly_name = "Магический суп"},
{ item_instance = "zdpwla_itfo_managa", friendly_name = "Манага"},
{ item_instance = "zdpwla_itfo_baron", friendly_name = "Победа барона"},
{ item_instance = "zdpwla_itfo_freedom", friendly_name = "Глоток свободы"},
{ item_instance = "zdpwla_itfo_oystersoup", friendly_name = "Суп из устриц"},
{ item_instance = "zdpwla_itfo_opus", friendly_name = "Опус Максима"},
{ item_instance = "yfauun_ithl_l_band", friendly_name = "Бандана"},
{ item_instance = "yfauun_ithl_m_helmet1", friendly_name = "Железный шлем"},
{ item_instance = "yfauun_ithl_m_helmet2", friendly_name = "Шлем наемника"},
{ item_instance = "yfauun_ithl_m_helmet3", friendly_name = "Шлем солдата"},
{ item_instance = "yfauun_ithl_m_helmet4", friendly_name = "Красный шлем"},
{ item_instance = "yfauun_ithl_m_helmet5", friendly_name = "Легкий шлем"},
{ item_instance = "yfauun_ithl_m_glasses", friendly_name = "Очки"},
{ item_instance = "yfauun_ithl_m_glasses1", friendly_name = "Очки1"},
{ item_instance = "yfauun_ithl_m_glasses2", friendly_name = "Очки2"},
{ item_instance = "yfauun_ithl_m_glasses3", friendly_name = "Очки3"},
{ item_instance = "jkztzd_itmw_1h_vlk_dagger", friendly_name = "Кинжал"},
{ item_instance = "jkztzd_itmw_1h_mace_l_01", friendly_name = "Кочерга"},
{ item_instance = "jkztzd_itmw_1h_bau_axe", friendly_name = "Серп"},
{ item_instance = "jkztzd_itmw_1h_vlk_mace", friendly_name = "Трость"},
{ item_instance = "jkztzd_itmw_1h_mace_l_03", friendly_name = "Дубина"},
{ item_instance = "jkztzd_itmw_1h_bau_mace", friendly_name = "Тяжелый сук"},
{ item_instance = "jkztzd_itmw_1h_vlk_axe", friendly_name = "Топорик"},
{ item_instance = "jkztzd_itmw_1h_mace_l_04", friendly_name = "Молот кузнеца"},
{ item_instance = "jkztzd_itmw_nagelknueppel", friendly_name = "Палица с шипами"},
{ item_instance = "jkztzd_itmw_1h_sword_l_03", friendly_name = "Волчий нож"},
{ item_instance = "yfauun_itar_neutral11", friendly_name = "Укрепленные кожаные доспехи"},
{ item_instance = "yfauun_itar_neutral22", friendly_name = "Одежда дезертира"},
{ item_instance = "yfauun_itar_neutral16", friendly_name = "Укрепленные латные доспехи"},
{ item_instance = "yfauun_itar_lolwetarmor", friendly_name = "Одеяние атамана"},
{ item_instance = "yfauun_itar_neutral12", friendly_name = "Отличные кожаные доспехи"},
{ item_instance = "yfauun_itar_neutral19", friendly_name = "Крутые латы"},
{ item_instance = "yfauun_itar_neutral15", friendly_name = "Отличные латы"},
{ item_instance = "jkztzd_itmw_sense", friendly_name = "Малая коса"}, 
{ item_instance = "jkztzd_itmw_1h_misc_sword", friendly_name = "Ржавый меч"},
{ item_instance = "jkztzd_itmw_nagelkeule", friendly_name = "Дубина с шипами"},
{ item_instance = "jkztzd_itmw_1h_knife_01", friendly_name = "Нож"},
{ item_instance = "jkztzd_itmw_shortsword1", friendly_name = "Короткий меч ополчения"},
{ item_instance = "jkztzd_itmw_shortsword2", friendly_name = "Военный короткий меч"},
{ item_instance = "jkztzd_itmw_1h_vlk_sword", friendly_name = "Шпага"},
{ item_instance = "jkztzd_itmw_1h_sld_axe", friendly_name = "Солдатский топор"},
{ item_instance = "jkztzd_itmw_shortsword3", friendly_name = "Короткий меч"},
{ item_instance = "jkztzd_itmw_shortsword4", friendly_name = "Волчий зуб"},
{ item_instance = "jkztzd_itmw_shortsword5", friendly_name = "Изысканный короткий меч"},
{ item_instance = "jkztzd_itmw_nagelkeule2", friendly_name = "Тяжелая дубина с шипами"},
{ item_instance = "jkztzd_itmw_schiffsaxt", friendly_name = "Корабельный топор"},
{ item_instance = "jkztzd_itmw_1h_common_01", friendly_name = "Простой меч"},
{ item_instance = "jkztzd_itmw_franciss", friendly_name = "Хороший кинжал"},
{ item_instance = "jkztzd_itmw_addon_pir1s", friendly_name = "Абордажная пика"},
{ item_instance = "jkztzd_itmw_1h_mil_sword", friendly_name = "Грубый палаш"},
{ item_instance = "jkztzd_itmw_1h_sld_sword", friendly_name = "Военный меч"},
{ item_instance = "jkztzd_itmw_kriegskeule", friendly_name = "Военная дубина"},
{ item_instance = "jkztzd_itmw_kriegshammer1", friendly_name = "Боевой молот"},
{ item_instance = "jkztzd_itmw_piratensaebel", friendly_name = "Пиратская абордажная сабля"},
{ item_instance = "jkztzd_itmw_schwert", friendly_name = "Грубый длинный меч"},
{ item_instance = "jkztzd_itmw_steinbrecher", friendly_name = "Дробитель камней"},
{ item_instance = "jkztzd_itmw_spicker", friendly_name = "Раскалыватель черепов"},
{ item_instance = "jkztzd_itmw_schwert1", friendly_name = "Изысканный меч"},
{ item_instance = "jkztzd_itmw_schwert2", friendly_name = "Длинный меч"},
{ item_instance = "jkztzd_itmw_schwert3", friendly_name = "Грубый полуторный меч"},
{ item_instance = "jkztzd_itmw_rapier", friendly_name = "Рапира"},
{ item_instance = "jkztzd_itmw_rubinklinge", friendly_name = "Рубиновый клинок"},
{ item_instance = "jkztzd_itmw_1h_special_01", friendly_name = "Длинный рудный меч"},
{ item_instance = "jkztzd_itmw_addonkeu", friendly_name = "Дубинка ветра"},
{ item_instance = "jkztzd_itmw_addon_pir1hm", friendly_name = "Абордажный нож"},
{ item_instance = "jkztzd_itmw_hacker_01", friendly_name = "Мачете"},
{ item_instance = "jkztzd_itmw_1h_pal_sword", friendly_name = "Меч офицера"},
{ item_instance = "jkztzd_itmw_doppelaxt", friendly_name = "Двойной топор"},
{ item_instance = "jkztzd_itmw_bartaxt", friendly_name = "Короткий бердыш"},
{ item_instance = "jkztzd_itmw_morgenstern", friendly_name = "Булава с шипами"},
{ item_instance = "jkztzd_itmw_schwert4", friendly_name = "Изысканный длинный меч"},
{ item_instance = "jkztzd_itmw_streitkolben", friendly_name = "Булава"},
{ item_instance = "jkztzd_itmw_runenschwert", friendly_name = "Рунный меч"},
{ item_instance = "jkztzd_itmw_rabenschnabel", friendly_name = "Клюв ворона"},
{ item_instance = "jkztzd_itmw_schwert5", friendly_name = "Изысканный полуторный меч"},
{ item_instance = "jkztzd_itmw_inquisitor", friendly_name = "Инквизитор"},
{ item_instance = "jkztzd_itmw_elbastardo", friendly_name = "Эль-бастардо"},
{ item_instance = "jkztzd_itmw_kriegshammer2", friendly_name = "Тяжелый боевой молот"},
{ item_instance = "jkztzd_itmw_meisterdegen", friendly_name = "Шпага мастера"},
{ item_instance = "jkztzd_itmw_orkschlaecht", friendly_name = "Убийца орков"},
{ item_instance = "jkztzd_itmw_1h_blessed_01", friendly_name = "Одноручный рудный клинок"},
{ item_instance = "jkztzd_itmw_1h_special_02", friendly_name = "Полуторный рудный меч"},
{ item_instance = "jkztzd_itmw_1h_special_03", friendly_name = "Рудный боевой клинок"},
{ item_instance = "jkztzd_itmw_addon_betty", friendly_name = "Бетти"},
{ item_instance = "jkztzd_itmw_1h_blessed_02", friendly_name = "Освященный рудный клинок"},
{ item_instance = "jkztzd_itmw_1h_blessed_03", friendly_name = "Гнев Инноса"},
{ item_instance = "jkztzd_itmw_1h_special_04", friendly_name = "Гнев Белиара"},
{ item_instance = "jkztzd_itmw_addon_stab01", friendly_name = "Посох мага"},
{ item_instance = "jkztzd_itmw_addon_stab02", friendly_name = "Магический посох"},
{ item_instance = "jkztzd_itmw_addon_stab03", friendly_name = "Посох Воды"},
{ item_instance = "jkztzd_itmw_addon_stab04", friendly_name = "Посох Ультара"},
{ item_instance = "jkztzd_itmw_addon_stab05", friendly_name = "Тайфун"},
{ item_instance = "jkztzd_itmw_addon_stab06", friendly_name = "Посох послушника"},
{ item_instance = "jkztzd_itmw_addon_stab07", friendly_name = "Посох мага воды"},
{ item_instance = "jkztzd_itmw_addon_stab08", friendly_name = "Посох мага воды2"},
{ item_instance = "jkztzd_itmw_2h_orcaxe_01", friendly_name = "Краш Панч"},
{ item_instance = "jkztzd_itmw_2h_orcaxe_02", friendly_name = "Краш Уррок"},
{ item_instance = "jkztzd_itmw_2h_orcaxe_03", friendly_name = "Краш Агаш"},
{ item_instance = "jkztzd_itmw_2h_orcaxe_04", friendly_name = "Краш Брокдар"},
{ item_instance = "jkztzd_itmw_2h_orcsword01", friendly_name = "Краш Варрок"},
{ item_instance = "jkztzd_itmw_2h_orcsword02", friendly_name = "Краш Каррок"},
{ item_instance = "jkztzd_itmw_2h_orcmace_08", friendly_name = "Краш Тарагх"},
{ item_instance = "jkztzd_itmw_2h_orcsword09", friendly_name = "Краш Хан"},
{ item_instance = "jkztzd_itmw_2h_bau_axe", friendly_name = "Топор лесоруба"},
{ item_instance = "jkztzd_itmw_richtstab", friendly_name = "Посох судьи"},
{ item_instance = "jkztzd_itmw_rangerstaff", friendly_name = "Посох Кольца воды"},
{ item_instance = "jkztzd_itmw_1h_nov_mace", friendly_name = "Боевой посох"},
{ item_instance = "jkztzd_itmw_2h_axe_l_01", friendly_name = "Кирка"},
{ item_instance = "jkztzd_itmw_1h_misc_axe", friendly_name = "Ржавый топор"},
{ item_instance = "jkztzd_itmw_2h_sword_m_01", friendly_name = "Ржавый двуручный меч"},
{ item_instance = "jkztzd_itmw_hellebarde", friendly_name = "Короткая алебарда"},
{ item_instance = "jkztzd_itmw_stabkeule", friendly_name = "Палица"},
{ item_instance = "jkztzd_itmw_zweihaender1", friendly_name = "Легкий двуручный меч"},
{ item_instance = "jkztzd_itmw_streitaxt1", friendly_name = "Легкий боевой топор"},
{ item_instance = "jkztzd_itmw_folteraxt", friendly_name = "Топор палача"},
{ item_instance = "jkztzd_itmw_addon2h", friendly_name = "Дубинка бури"},
{ item_instance = "jkztzd_itmw_2h_sld_axe", friendly_name = "Тяжелый солдатский топор"},
{ item_instance = "jkztzd_itmw_2h_sld_sword", friendly_name = "Солдатский двуручный меч"},
{ item_instance = "jkztzd_itmw_2h_pal_sword", friendly_name = "Изысканный двуручный меч"},
{ item_instance = "jkztzd_itmw_zweihaender2", friendly_name = "Двуручный меч"},
{ item_instance = "jkztzd_itmw_streitaxt2", friendly_name = "Боевой топор"},
{ item_instance = "jkztzd_itmw_zweihaender4", friendly_name = "Тяжелый двуручный меч"},
{ item_instance = "jkztzd_itmw_schlachtaxt", friendly_name = "Военный топор"},
{ item_instance = "jkztzd_itmw_hacker_03", friendly_name = "Гигантское мачете"},
{ item_instance = "jkztzd_itmw_krummschwert", friendly_name = "Абордажная сабля"},
{ item_instance = "jkztzd_itmw_barbarenstr", friendly_name = "Боевой топор варваров"},
{ item_instance = "jkztzd_itmw_sturmbringer", friendly_name = "Верный друг"},
{ item_instance = "jkztzd_itmw_berserkeraxt", friendly_name = "Топор берсеркера"},
{ item_instance = "jkztzd_itmw_2h_blessed_01", friendly_name = "Грубый рудный клинок"},
{ item_instance = "jkztzd_itmw_2h_blessed_02", friendly_name = "Меч ордена"},
{ item_instance = "jkztzd_itmw_2h_special_02", friendly_name = "Тяжелый рудный двуручник"},
{ item_instance = "jkztzd_itmw_addon_pir2hax", friendly_name = "Крушитель досок"},
{ item_instance = "jkztzd_itmw_zweihaender3", friendly_name = "Сила Рун"},
{ item_instance = "jkztzd_itmw_drachenschne", friendly_name = "Гроза драконов"},
{ item_instance = "jkztzd_itmw_2h_blessed_03", friendly_name = "Святой палач"},
{ item_instance = "jkztzd_itmw_2h_special_01", friendly_name = "Королевский Клинок"},	
{ item_instance = "jkztzd_itmw_2h_special03", friendly_name = "Тяжелый рудный боевой клинок"},	
{ item_instance = "jkztzd_itmw_2h_special_04", friendly_name = "Двуручный Убийца Драконов"},	
{ item_instance = "jkztzd_itmw_drachenschne1", friendly_name = "Меч Генерала"},	
{ item_instance = "ooltyb_itmi_wedel", friendly_name = "Пальмовый веер"},	
{ item_instance = "ooltyb_itmi_joint_1", friendly_name = "Вялый джо"},	
{ item_instance = "ooltyb_itmi_joint_2", friendly_name = "Северный темный"},	
{ item_instance = "ooltyb_itmi_joint_3", friendly_name = "Мечта рудокопа"},	
{ item_instance = "ooltyb_itmi_stuff_pipe_01", friendly_name = "Трубка"},	
{ item_instance = "ooltyb_itmi_stuff_barbknife_01", friendly_name = "Бритвенный нож"},	
{ item_instance = "ooltyb_itmi_stuff_plate_01", friendly_name = "Тарелка"},	
{ item_instance = "ooltyb_itmi_stuff_candel_01", friendly_name = "Подсвечник"},	
{ item_instance = "ooltyb_itmi_stuff_cup_01", friendly_name = "Кубок"},
{ item_instance = "ooltyb_itmi_stuff_cup_02", friendly_name = "Бокал"},
{ item_instance = "ooltyb_itmi_stuff_silverware_01", friendly_name = "Столовый набор"},
{ item_instance = "ooltyb_itmi_stuff_mug_01", friendly_name = "Кружка"},
{ item_instance = "ooltyb_itmi_stuff_amphore_01", friendly_name = "Амфора"},
{ item_instance = "ooltyb_itmi_stuff_idol_ogront_01", friendly_name = "Статуя"},
{ item_instance = "ooltyb_itmi_alchemy_quicksilver_01", friendly_name = "Ртуть"},
{ item_instance = "ooltyb_itmi_alchemy_salt_01", friendly_name = "Соль"},
{ item_instance = "ooltyb_itmi_alchemy_syrianoil_01", friendly_name = "Масло"},
{ item_instance = "ooltyb_itmi_alchemy_alcohol_01", friendly_name = "Чистый спирт"},
{ item_instance = "ooltyb_itat_addon_bckopf", friendly_name = "Голова богомола"},
{ item_instance = "ooltyb_itat_meatbugflesh", friendly_name = "Мясо жука"},
{ item_instance = "ooltyb_itat_sheepfur", friendly_name = "Овечья шкура"},
{ item_instance = "ooltyb_itat_wolffur", friendly_name = "Волчья шкура"},
{ item_instance = "ooltyb_itat_bugmandibles", friendly_name = "Мандибулы полевого хищника"},
{ item_instance = "ooltyb_itat_claw", friendly_name = "Челюсти"},
{ item_instance = "ooltyb_itat_lurkerclaw", friendly_name = "Челюсть луркера"},
{ item_instance = "ooltyb_itat_teeth", friendly_name = "Зубы"},
{ item_instance = "ooltyb_itat_crawlermandibles", friendly_name = "Мандибулы краулера"},
{ item_instance = "ooltyb_itat_wing", friendly_name = "Крылья"},
{ item_instance = "ooltyb_itat_sting", friendly_name = "Жало"},
{ item_instance = "ooltyb_itat_lurkerskin", friendly_name = "Шкура рептилии"},
{ item_instance = "ooltyb_itat_wargfur", friendly_name = "Шкура варга"},
{ item_instance = "ooltyb_itat_addon_keilerfur", friendly_name = "Шкура кабана"},
{ item_instance = "ooltyb_itat_drgsnapperhorn", friendly_name = "Рог драконьего снеппера"},
{ item_instance = "ooltyb_itat_crawlerplate", friendly_name = "Панцирь краулера"},
{ item_instance = "ooltyb_itat_shadowfur", friendly_name = "Шкура мракориса"},
{ item_instance = "ooltyb_itat_sharkskin", friendly_name = "Шкура болотной акулы"},
{ item_instance = "ooltyb_itat_trollfur", friendly_name = "Шкура тролля"},
{ item_instance = "ooltyb_itat_trollblackfur", friendly_name = "Шкура черного тролля"},
{ item_instance = "ooltyb_itat_waranfiretongue", friendly_name = "Огненный язык"},
{ item_instance = "ooltyb_itat_shadowhorn", friendly_name = "Рог мракориса"},
{ item_instance = "ooltyb_itat_sharkteeth", friendly_name = "Зубы болотной акулы"},
{ item_instance = "ooltyb_itat_trolltooth", friendly_name = "Клык тролля"},
{ item_instance = "ooltyb_itat_stonegolemheart", friendly_name = "Сердце каменного голема"},
{ item_instance = "ooltyb_itat_firegolemheart", friendly_name = "Сердце огненного голема"},
{ item_instance = "ooltyb_itat_icegolemheart", friendly_name = "Сердце Ледяного голема"},
{ item_instance = "ooltyb_itat_goblinbone", friendly_name = "Кость гоблина"},
{ item_instance = "ooltyb_itat_skeletonbone", friendly_name = "Кость скелета"},
{ item_instance = "ooltyb_itat_demonheart", friendly_name = "Сердце демона"},
{ item_instance = "ooltyb_itat_undeaddragonsoulstone", friendly_name = "Камень души дракона-нежити"},
{ item_instance = "ooltyb_itat_icedragonheart", friendly_name = "Сердце ледяного дракона"},
{ item_instance = "ooltyb_itat_rockdragonheart", friendly_name = "Сердце каменного дракона"},
{ item_instance = "ooltyb_itat_swampdragonheart", friendly_name = "Сердце болотного дракона"},
{ item_instance = "ooltyb_itat_firedragonheart", friendly_name = "Сердце огненного дракона"},
{ item_instance = "ooltyb_itat_dragonblood", friendly_name = "Драконья кровь"},
{ item_instance = "ooltyb_itat_dragonscale", friendly_name = "Чешуя дракона"},
{ item_instance = "ooltyb_itat_fat", friendly_name = "Жир"},
{ item_instance = "yfauun_itar_quiver", friendly_name = "Колчан"},
{ item_instance = "itlstorch", friendly_name = "Факел"},
{ item_instance = "itlstorchburning", friendly_name = "Горящий факел"},
{ item_instance = "itlstorchburned", friendly_name = "Факел1"},
{ item_instance = "itlstorchfirespit", friendly_name = "Факел2"},
{ item_instance = "ooltyb_itke_lockpick", friendly_name = "Отмычка"},
{ item_instance = "ooltyb_itmi_stomper", friendly_name = "Давилка"},
{ item_instance = "ooltyb_itmi_runeblank", friendly_name = "Руна"},
{ item_instance = "ooltyb_itmi_pliers", friendly_name = "Щипцы"},
{ item_instance = "ooltyb_itmi_flask", friendly_name = "Мензурка"},
{ item_instance = "ooltyb_itmi_hammer", friendly_name = "Молот"},
{ item_instance = "ooltyb_itmi_scoop", friendly_name = "Ложка"},
{ item_instance = "ooltyb_itmi_pan", friendly_name = "Сковорода"},
{ item_instance = "ooltyb_itmi_saw", friendly_name = "Пила"},
{ item_instance = "ooltyb_itmiswordraw", friendly_name = "Обработанная сталь"},
{ item_instance = "ooltyb_itmiswordrawhot", friendly_name = "Раскаленная сталь"},
{ item_instance = "ooltyb_itmiswordbladehot", friendly_name = "Раскаленный клинок"},
{ item_instance = "ooltyb_itmiswordblade", friendly_name = "Клинок"},
{ item_instance = "ooltyb_itmi_broom", friendly_name = "Метла"},
{ item_instance = "ooltyb_itmi_lute", friendly_name = "Лютня"},
{ item_instance = "ooltyb_itmi_brush", friendly_name = "Щетка"},
{ item_instance = "ooltyb_itmi_joint", friendly_name = "Косяк из болотной травы"},
{ item_instance = "ooltyb_itmi_packet", friendly_name = "Пакет"},
{ item_instance = "ooltyb_itmi_pocket", friendly_name = "Кожаный кошелек"}, 
{ item_instance = "ooltyb_itmi_nugget", friendly_name = "Кусок руды"}, 
{ item_instance = "ooltyb_itmi_gold", friendly_name = "Золото"}, 
{ item_instance = "ooltyb_itmi_oldcoin", friendly_name = "Старая монета"}, 
{ item_instance = "ooltyb_itmi_goldcandleholder", friendly_name = "Золотой подсвечник"}, 
{ item_instance = "ooltyb_itmi_goldnecklace", friendly_name = "Золотое ожерелье"}, 
{ item_instance = "ooltyb_itmi_silverring", friendly_name = "Серебряное кольцо"}, 
{ item_instance = "ooltyb_itmi_silvercup", friendly_name = "Серебряный кубок"}, 
{ item_instance = "ooltyb_itmi_silverplate", friendly_name = "Серебряная тарелка"}, 
{ item_instance = "ooltyb_itmi_goldplate", friendly_name = "Золотая тарелка"},  
{ item_instance = "ooltyb_itmi_goldcup", friendly_name = "Золотой кубок"},  
{ item_instance = "ooltyb_itmi_bloodcup_mis", friendly_name = "Кровавый кубок"},  
{ item_instance = "ooltyb_itmi_goldring", friendly_name = "Золотое кольцо"},  
{ item_instance = "ooltyb_itmi_silverchalice", friendly_name = "Серебряная чаша"}, 
{ item_instance = "ooltyb_itmi_jewelerychest", friendly_name = "Шкатулка с драгоценностями"}, 
{ item_instance = "ooltyb_itmi_goldchalice", friendly_name = "Золотая чаша"}, 
{ item_instance = "ooltyb_itmi_goldchest", friendly_name = "Шкатулка"}, 
{ item_instance = "ooltyb_itmi_innosstatue", friendly_name = "Статуя Инноса"}, 
{ item_instance = "ooltyb_itmi_sextant", friendly_name = "Секстант"}, 
{ item_instance = "ooltyb_itmi_silvercandleholder", friendly_name = "Серебряный подсвечник"}, 
{ item_instance = "ooltyb_itmi_silvernecklace", friendly_name = "Серебряное ожерелье"}, 
{ item_instance = "ooltyb_itmi_sulfur", friendly_name = "Сера"}, 
{ item_instance = "ooltyb_itmi_quartz", friendly_name = "Ледяной кварц"}, 
{ item_instance = "ooltyb_itmi_pitch", friendly_name = "Смола"}, 
{ item_instance = "ooltyb_itmi_rockcrystal", friendly_name = "Горный хрусталь"}, 
{ item_instance = "ooltyb_itmi_aquamarine", friendly_name = "Горный хрусталь"},
{ item_instance = "ooltyb_itmi_holywater", friendly_name = "Святая вода"},
{ item_instance = "ooltyb_itmi_coal", friendly_name = "Уголь"},
{ item_instance = "ooltyb_itmi_darkpearl", friendly_name = "Черный жемчуг"},
{ item_instance = "ooltyb_itmi_apfeltabak", friendly_name = "Яблочный табак"},
{ item_instance = "ooltyb_itmi_pilztabak", friendly_name = "Грибной табак"},
{ item_instance = "ooltyb_itmi_doppeltabak", friendly_name = "Двойное яблоко"},
{ item_instance = "ooltyb_itmi_honigtabak", friendly_name = "Медовый табак"},
{ item_instance = "ooltyb_itmi_sumpftabak", friendly_name = "Травяной табак"},
{ item_instance = "ooltyb_itmi_rake", friendly_name = "Мотыга"},
{ item_instance = "ooltyb_itmi_goldnugget_addon", friendly_name = "Золотой самородок"},
{ item_instance = "ooltyb_itmi_addon_whitepearl", friendly_name = "Жемчужина"},
{ item_instance = "ooltyb_itmi_remi", friendly_name = "Речной мирт"},
{ item_instance = "ooltyb_itmi_remi2", friendly_name = "Моллюск"},
{ item_instance = "ooltyb_itmi_remi1", friendly_name = "Иловый мирт"},
{ item_instance = "ooltyb_itmi_addon_joint_01", friendly_name = "Зеленый послушник"},
{ item_instance = "ooltyb_itmi_skull", friendly_name = "Череп"},
{ item_instance = "ooltyb_itmi_iecello", friendly_name = "Виолончель"},
{ item_instance = "ooltyb_itmi_m_ignot", friendly_name = "Магический слиток"},
{ item_instance = "ooltyb_itmi_s_ignot", friendly_name = "Слиток"},
{ item_instance = "ooltyb_itmi_m_wire", friendly_name = "Проволока"},
{ item_instance = "ooltyb_itmi_rivet", friendly_name = "Заклепка"},
{ item_instance = "ooltyb_itmi_bijouterie", friendly_name = "Бижутерия"},
{ item_instance = "ooltyb_itmi_linkage", friendly_name = "Рычажный механизм"},
{ item_instance = "zdpwla_itmi_bucket", friendly_name = "Ведро"},
{ item_instance = "ooltyb_itmi_nail", friendly_name = "Гвоздь"},
{ item_instance = "ooltyb_itmi_buckle", friendly_name = "Пряжка"},
{ item_instance = "ooltyb_itmi_goldignot", friendly_name = "Золотой слиток"},
{ item_instance = "ooltyb_itmi_t_leather", friendly_name = "Тонкая кожа"},
{ item_instance = "ooltyb_itmi_leather", friendly_name = "Кожа"},
{ item_instance = "ooltyb_itmi_l_leather", friendly_name = "Кожаная лента"},
{ item_instance = "ooltyb_itmi_linen_holst", friendly_name = "Льняная ткань"},
{ item_instance = "ooltyb_itmi_whool_holst", friendly_name = "Сукно"},
{ item_instance = "ooltyb_itmi_fiber", friendly_name = "Нить"},
{ item_instance = "yvnzmz_itmi_file", friendly_name = "Напильник"},
{ item_instance = "yvnzmz_itmi_pierser", friendly_name = "Прошивня"},
{ item_instance = "yvnzmz_itmi_chisel", friendly_name = "Зубило"},
{ item_instance = "yvnzmz_itmi_clay", friendly_name = "Опока"},
{ item_instance = "yvnzmz_itmi_pot", friendly_name = "Тигель"},
{ item_instance = "yvnzmz_itmi_drawbd", friendly_name = "Волочильная доска"},
{ item_instance = "yvnzmz_itmi_needle", friendly_name = "Игла"},
{ item_instance = "yvnzmz_itmi_punch", friendly_name = "Пробойник"},
{ item_instance = "yvnzmz_itmi_pliers", friendly_name = "Клещи"},
{ item_instance = "yvnzmz_itmi_spherehammer", friendly_name = "Молот со сферическим бойком"},
{ item_instance = "ooltyb_itmi_obrabotder", friendly_name = "Обработанная древесина"},
{ item_instance = "ooltyb_itmi_sheep", friendly_name = "Шерсть"},
{ item_instance = "ooltyb_itmi_tkaswa", friendly_name = "Ткань из болотника"},
{ item_instance = "ooltyb_itmi_nitswa", friendly_name = "Нити из болотника"},
{ item_instance = "zdpwla_itmi_vinegar", friendly_name = "Уксус"},
{ item_instance = "zdpwla_itmi_alchbasis", friendly_name = "Алхимическая основа"},
{ item_instance = "zdpwla_itmi_alchsub", friendly_name = "Алхимический субстрат"},
{ item_instance = "zdpwla_itmi_acid", friendly_name = "Кислота"},
{ item_instance = "zdpwla_itmi_dye", friendly_name = "Краска"},
{ item_instance = "ooltyb_itmi_scissors", friendly_name = "Ножницы"},
{ item_instance = "ooltyb_itmi_fishing", friendly_name = "Удочка"},
{ item_instance = "ooltyb_itmi_paper", friendly_name = "Бумага"},
{ item_instance = "ooltyb_itmi_wood", friendly_name = "Древесина"},
{ item_instance = "ooltyb_itmi_wheat", friendly_name = "Пшеница"},
{ item_instance = "ooltyb_itmi_magicore", friendly_name = "Магическая крошка"},
{ item_instance = "ooltyb_itmi_rubin", friendly_name = "Рубин"},
{ item_instance = "ooltyb_itmi_iron", friendly_name = "Кусок железной руды"},
{ item_instance = "ooltyb_itmi_honeycomb", friendly_name = "Соты"},
{ item_instance = "ooltyb_itmi_flour", friendly_name = "Мешок муки"},
{ item_instance = "ooltyb_itmi_dough", friendly_name = "Тесто"},
{ item_instance = "ooltyb_itmi_skinner_tools", friendly_name = "Инструменты кожевника"},
{ item_instance = "ooltyb_itmi_palatka", friendly_name = "Палатка"},	
{ item_instance = "ooltyb_itmi_koster", friendly_name = "Костер"},	
{ item_instance = "oolooltyb_itmi_boot", friendly_name = "Весельная лодка"},	
{ item_instance = "ooltyb_itmi_bottle_empty", friendly_name = "Пустая бутылка"},
{ item_instance = "ooltyb_itmi_dirty_water", friendly_name = "Грязная вода"},
{ item_instance = "ooltyb_itmi_taran", friendly_name = "Таран"},
{ item_instance = "ooltyb_itmi_hirg", friendly_name = "Хирургические инструменты"},
{ item_instance = "ooltyb_itmi_bint", friendly_name = "Бинт"},
{ item_instance = "ooltyb_itmi_priparka", friendly_name = "Припарка"},
{ item_instance = "ooltyb_itmi_recipe1", friendly_name = "Рецепт - мантии магов воды"},
{ item_instance = "ooltyb_itmi_recipe2", friendly_name = "Рецепт - мантии магов огня"},
{ item_instance = "ooltyb_itmi_jointrecipe_1", friendly_name = "Обработка болотника (Рецепт)"},
{ item_instance = "ooltyb_itmi_jointrecipe1", friendly_name = "Обработка болотника (Рецепт)"},
{ item_instance = "OOLTYB_ITMI_JOINTRECIPE2", friendly_name = "Секрет косяков (Рецепт)"},
{ item_instance = "ooltyb_itmi_opusrecipe", friendly_name = "Опус Максима (Рецепт)"},
{ item_instance = "ooltyb_itmi_silvernugget", friendly_name = "Серебряный самородок"},
{ item_instance = "ooltyb_itmi_rudecoin", friendly_name = "Рудная фишка"},
{ item_instance = "zdpwla_itpl_weed", friendly_name = "Сорняк"},
{ item_instance = "zdpwla_itpl_beet", friendly_name = "Свекла"},
{ item_instance = "zdpwla_itpl_swampherb", friendly_name = "Болотник"},
{ item_instance = "zdpwla_itpl_mana_herb_01", friendly_name = "Огненная крапива"},	
{ item_instance = "zdpwla_itpl_mana_herb_02", friendly_name = "Огненная трава"},	
{ item_instance = "zdpwla_itpl_mana_herb_03", friendly_name = "Огненный корень"},
{ item_instance = "zdpwla_itpl_health_herb_01", friendly_name = "Лечебное растение"},
{ item_instance = "zdpwla_itpl_health_herb_02", friendly_name = "Лечебная трава"},
{ item_instance = "zdpwla_itpl_health_herb_03", friendly_name = "Лечебный корень"},
{ item_instance = "zdpwla_itpl_dex_herb_01", friendly_name = "Ягода гоблина"},
{ item_instance = "zdpwla_itpl_strength_herb_01", friendly_name = "Драконий корень"},
{ item_instance = "zdpwla_itpl_speed_herb_01", friendly_name = "Трава глорха"},
{ item_instance = "zdpwla_itpl_mushroom_01", friendly_name = "Темный гриб"},
{ item_instance = "zdpwla_itpl_mushroom_04", friendly_name = "Астральный гриб"},
{ item_instance = "zdpwla_itpl_mushroom_02", friendly_name = "Мясной гриб"},
{ item_instance = "zdpwla_itpl_blueplant", friendly_name = "Синее растение"},
{ item_instance = "zdpwla_itpl_forestberry", friendly_name = "Лесная ягода"},
{ item_instance = "zdpwla_itpl_planeberry", friendly_name = "Дикая ягода"},
{ item_instance = "zdpwla_itpl_temp_herb", friendly_name = "Полевое растение"},
{ item_instance = "zdpwla_itpl_perm_herb", friendly_name = "Коронное растение"},
{ item_instance = "zdpwla_itpl_lean", friendly_name = "Лен"},
{ item_instance = "zeqfrn_itpo_mana_01", friendly_name = "Эссенция маны"},
{ item_instance = "zeqfrn_itpo_mana_02", friendly_name = "Экстракт маны"},
{ item_instance = "zeqfrn_itpo_mana_03", friendly_name = "Эликсир маны"}, 
{ item_instance = "zeqfrn_itpo_health_01", friendly_name = "Лечебная эссенция"},
{ item_instance = "zeqfrn_itpo_health_02", friendly_name = "Лечебный экстракт"},
{ item_instance = "zeqfrn_itpo_health_03", friendly_name = "Лечебный эликсир"},
{ item_instance = "zeqfrn_itpo_perm_dex", friendly_name = "Эликсир ловкости"},
{ item_instance = "zeqfrn_itpo_perm_health", friendly_name = "Эликсир жизни"},
{ item_instance = "zeqfrn_itpo_perm_mana", friendly_name = "Эликсир духа"},
{ item_instance = "zeqfrn_itpo_speed", friendly_name = "Зелье ускорения"},
{ item_instance = "zeqfrn_itpo_megadrink", friendly_name = "Зелье ускорения"},
{ item_instance = "zeqfrn_itpo_bleach", friendly_name = "Очищающая микстура"},
{ item_instance = "zeqfrn_itpo_antidote", friendly_name = "Антидот"},
{ item_instance = "jkztzd_itrw_bow_l_01", friendly_name = "Короткий лук"},
{ item_instance = "jkztzd_itrw_arrow", friendly_name = "Стрела"},
{ item_instance = "jkztzd_itrw_sld_bow", friendly_name = "Солдатский лук"},
{ item_instance = "jkztzd_itrw_bow_l_02", friendly_name = "Ивовый лук"},
{ item_instance = "jkztzd_itrw_bow_l_03", friendly_name = "Охотничий лук"},
{ item_instance = "jkztzd_itrw_bow_l_04", friendly_name = "Вязовый лук"},
{ item_instance = "jkztzd_itrw_bow_m_01", friendly_name = "Композитный лук"},
{ item_instance = "jkztzd_itrw_bow_m_02", friendly_name = "Ясеневый лук"},
{ item_instance = "jkztzd_itrw_bow_m_03", friendly_name = "Длинный лук"},
{ item_instance = "jkztzd_itrw_bow_m_04", friendly_name = "Буковый лук"},
{ item_instance = "jkztzd_itrw_bow_h_01", friendly_name = "Костяной лук"},
{ item_instance = "jkztzd_itrw_bow_h_02", friendly_name = "Дубовый лук"},
{ item_instance = "jkztzd_itrw_bow_h_03", friendly_name = "Военный лук"},
{ item_instance = "jkztzd_itrw_bow_h_04", friendly_name = "Драконий лук"},
{ item_instance = "jkztzd_itrw_crossbow_l_01", friendly_name = "Охотничий арбалет"},
{ item_instance = "jkztzd_itrw_mil_crossbow", friendly_name = "Арбалет"},
{ item_instance = "jkztzd_itrw_crossbow_l_02", friendly_name = "Легкий арбалет"},
{ item_instance = "jkztzd_itrw_crossbow_m_01", friendly_name = "Арбалет ополчения"},
{ item_instance = "jkztzd_itrw_crossbow_m_02", friendly_name = "Военный арбалет"},
{ item_instance = "jkztzd_itrw_crossbow_h_01", friendly_name = "Тяжелый арбалет"},
{ item_instance = "jkztzd_itrw_crossbow_h_02", friendly_name = "Арбалет охотника на драконов"},
{ item_instance = "jkztzd_itmw_2h_forka_012", friendly_name = "Вилы"},
{ item_instance = "jkztzd_itmw_1h_knife_01", friendly_name = "Нож"},
{ item_instance = "ooltyb_itmi_parchment", friendly_name = "Пергамент"},
{ item_instance = "jkztzd_itrw_bolt", friendly_name = "Болт"},
{ item_instance = "ooltyb_itmi_sh", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh1", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh2", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh3", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh4", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh5", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh6", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh7", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh8", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh9", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh10", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh11", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh12", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh13", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_sh14", friendly_name = "Конец"},
{ item_instance = "ooltyb_itmi_stroy", friendly_name = "Строительные материалы"},
{ item_instance = "ooltyb_itmi_key1", friendly_name = "Ключ1"},
{ item_instance = "ooltyb_itmi_key2", friendly_name = "Ключ2"},
{ item_instance = "ooltyb_itmi_key3", friendly_name = "Ключ3"},
{ item_instance = "ooltyb_itmi_key4", friendly_name = "Ключ4"},
{ item_instance = "ooltyb_itmi_key5", friendly_name = "Ключ5"},
{ item_instance = "ooltyb_itmi_key6", friendly_name = "Ключ6"},
{ item_instance = "ooltyb_itmi_key7", friendly_name = "Ключ7"},
{ item_instance = "ooltyb_itmi_key8", friendly_name = "Ключ8"},
{ item_instance = "ooltyb_itmi_key9", friendly_name = "Ключ9"}, -- занято нахуй
{ item_instance = "ooltyb_itmi_key10", friendly_name = "Ключ10"},
{ item_instance = "ooltyb_itmi_key11", friendly_name = "Ключ11"},
{ item_instance = "ooltyb_itmi_key12", friendly_name = "Ключ12"},
{ item_instance = "ooltyb_itmi_key13", friendly_name = "Ключ13"},
{ item_instance = "ooltyb_itmi_key14", friendly_name = "Ключ14"},
{ item_instance = "ooltyb_itmi_key16", friendly_name = "Ключ15"},
{ item_instance = "ihpiwn_itsc_firebolt", friendly_name = "Cвиток - огненная стрела"},
{ item_instance = "mhahgh_itwr_addon_runemaking_kdf_circ1", friendly_name = "Книга формул круга огня - 1 круг"},
{ item_instance = "mhahgh_itwr_addon_mcelixier_01", friendly_name = "Книга формул"},
{ item_instance = "ihpiwn_itsc_icebolt", friendly_name = "Свиток - ледяная стрела"}, 
{ item_instance = "ihpiwn_itsc_lightheal", friendly_name = "Свиток - легкое лечение"},
{ item_instance = "ihpiwn_itsc_light", friendly_name = "Свиток - свет"},
{ item_instance = "ihpiwn_itsc_zap", friendly_name = "Свиток - молния"},
{ item_instance = "ihpiwn_itsc_instantfireball", friendly_name = "Свиток - огненный шар"},
{ item_instance = "ihpiwn_itsc_icelance", friendly_name = "Свиток - ледяное копье"},
{ item_instance = "saqtsh_itru_icebolt", friendly_name = "Руна - ледяная стрела"},
{ item_instance = "saqtsh_itru_firebolt", friendly_name = "Руна - огненная стрела"},
{ item_instance = "saqtsh_itru_light", friendly_name = "Руна - свет"}, 
{ item_instance = "saqtsh_itru_lightheal", friendly_name = "Руна - легкое лечение"},
{ item_instance = "saqtsh_itru_instantfireball", friendly_name = "Руна - огненный шар"},
{ item_instance = "saqtsh_itru_icelance", friendly_name = "Руна - ледяное копье"},
{ item_instance = "mhahgh_itwr_addon_runemaking_kdw_circ1", friendly_name = "Книга формул круга воды - 1 круг"},
{ item_instance = "mhahgh_itwr_addon_runemaking_kdf_circ2", friendly_name = "Книга формул круга огня - 2 круг"},
{ item_instance = "mhahgh_itwr_addon_runemaking_kdw_circ2", friendly_name = "Книга формул круга воды - 2 круг"},
{ item_instance = "yfauun_sld_armor_l3", friendly_name = "Наплечник наемника"},
{ item_instance = "yfauun_grd_armor_h3", friendly_name = "Укрепленный доспех стражника"}, 
{ item_instance = "saqtsh_itru_zap", friendly_name = "Руна - малая молния"}, 
{ item_instance = "saqtsh_itru_windfist", friendly_name = "Руна - кулак ветра"}, 
{ item_instance = "saqtsh_itru_sleep", friendly_name = "Руна - сон"}, 
{ item_instance = "saqtsh_itru_mediumheal", friendly_name = "Руна - среднее лечение"},
{ item_instance = "yfauun_itar_kdw_s", friendly_name = "Облачение послушника круга воды"}, 
{ item_instance = "yfauun_itar_relaiker", friendly_name = "Мантия кочевника"}, 
{ item_instance = "yfauun_itar_relaiker1", friendly_name = "Мантия кочевника(к)"}, 

{item_instance = "yvnzmz_itmi_bolvanka", friendly_name = "Болванка для ключей"}, 
{ item_instance = "ooltyb_chest_key1", friendly_name = "Ключ (с) - трактир НЛ"}, 
{ item_instance = "ooltyb_chest_key2", friendly_name = "Ключ (с) - генерал"}, 
{ item_instance = "ooltyb_chest_key3", friendly_name = "Ключ (с) - маги НЛ-1"}, 
{ item_instance = "ooltyb_chest_key4", friendly_name = "Ключ (с) - маги НЛ-2"}, 
{ item_instance = "ooltyb_chest_key5", friendly_name = "Ключ (с) - башня теней"}, 
{ item_instance = "ooltyb_chest_key6", friendly_name = "Ключ (с) - склад стражи"}, 
{ item_instance = "ooltyb_chest_key7", friendly_name = "Ключ (с) - маги огня"}, 
{ item_instance = "ooltyb_chest_key8", friendly_name = "Ключ (с) - рудный схрон"}, 
{ item_instance = "ooltyb_chest_key9", friendly_name = "Ключ (с) - номер 9"}, -- занято нахуй
{ item_instance = "yvnzmz_itmi_zamok", friendly_name = "Замок"},
{ item_instance = "ooltyb_itmi_chest1", friendly_name = "Сундук"}, 
{ item_instance = "ooltyb_itmi_chest2", friendly_name = "Крепкий сундук"}, 
{ item_instance = "ooltyb_itmi_chest3", friendly_name = "Прочный сундук"}, 

{ item_instance = "OOLTYB_ITMI_BIJOUTERIE", friendly_name = "Бижутерия1"},
{ item_instance = "zdpwla_itmi_beltum", friendly_name = "Рунный пояс мастера"},
{ item_instance = "zdpwla_itmi_belthm", friendly_name = "Рунный пояс мага"},
{ item_instance = "zdpwla_itmi_beltlm", friendly_name = "Рунный пояс ученика"},
{ item_instance = "ooltyb_itmi_mage1", friendly_name = "Заготовка - 1 круг"},
{ item_instance = "ooltyb_itmi_mage2", friendly_name = "Заготовка - 2 круг"},
{ item_instance = "ooltyb_itmi_mage3", friendly_name = "Заготовка - 3 круг"},
{ item_instance = "ooltyb_itmi_mage4", friendly_name = "Заготовка - 4 круг"},
{ item_instance = "ooltyb_itmi_mage5", friendly_name = "Заготовка - 5 круг"},
{ item_instance = "ooltyb_itmi_mage6", friendly_name = "Заготовка - 6 круг"},

{ item_instance = "ooltyb_itmi_recipeswsl", friendly_name = "Чертеж брони теней"},
{ item_instance = "ooltyb_itmi_recipetfnl", friendly_name = "Чертеж брони воров"},
{ item_instance = "ooltyb_itmi_recipemynl", friendly_name = "Чертеж брони наемников"},
{ item_instance = "ooltyb_itmi_recipegdsl", friendly_name = "Чертеж брони стражников"},

}

function GetItemName( item_instance )
	if item_instance and type( item_instance ) == "string" then
		for key, item in ipairs( inst_Items ) do
			if( string.lower( item_instance ) == item.item_instance ) then
				return item.friendly_name
			end
		end
	end
	return item_instance
end

function GetItemCode( friendly_name )
	if friendly_name and type( friendly_name ) == "string" then
		for key, item in ipairs( inst_Items ) do
			if( string.lower( friendly_name ) == item.friendly_name ) then
				return item.item_instance
			end
		end
	end
	return friendly_name
end