local VobIDs = {};
local VobModels = {};
local SavedVobs = {};
SS_ENABLED = false;
local Objectlist={
"Door_Wooden.mds",
"ChestBig_OCCRateLargeLocked.mds",
"ITLS_TORCHBURNING_01.3DS",
"ITLS_TORCHBURNING.3DS",
"KREUTZ2.3DS",
"ARROWTRAIL.3DS",
"OC_LOB_GATE_SMALL2.3DS",
"OC_LOB_GATE_BIG.3DS",
"DOOR_NW_RICH_01.MDS",
"DOOR_NW_NORMAL_01.MDS",
"EVT_OC_INNERMAINGATE.3DS",
"CAGEDOORS.MDS",
"EVT_OC_MAINGATE01_01.MDS",
"EVT_OC_MAINGATE02_02.MDS",
"EVT_NC_LOCKOUT_MOVER_01.MDS",
"EVT_NC_MAINGATE01_MOVER.MDS",
"EVT_ORCGRAVYARD_MOVER_01.MDS",
"OW_ORC_MAINGATE_01.MDS",
"EVT_ORC_GATE_02.MDS",
"EVT_OW_MOUNTAINRUIN_01.MDS",
"EVT_OW_FOKUS_GATE_MOVER_01.MDS",
"EVT_AM_LOB_GATE_BIG.MDS",
"DOOR_NW_NORMAL_01.MDS",
"G3_ZU_G2_HAUS 03B.3DS",
"GAMMELBUDE.3DS",
"GMM_HUT.3DS",
"HUNTERS_HUT500X950.3DS",
"PFAHLZAUN_10.3DS",
"ZAUNPFAHLZAUN_EINGANG_B.3DS",
"AW_CRATEPILE_01.3DS",
"AW_CRATE_01.3DS",
"BEAM_G.3DS",
"BEAM_ML.3DS",
"BEAM_MS.3DS",
"BEAM_T.3DS",
"NW_MISC_INNOS_GROUND_01.3DS",
"COLDUMMY.3DS",
"COLDUMMY.3DS",
"CR_DI_OPENEGG.3DS",
"CR_DI_SLIME.3DS",
"CYLINDERFX.3DS",
"CYLINDERFX.3DS",
"DEMON_DIE.3DS",
"DEMON_DIE.3DS",
"DT_2ND_FLOOR_BANNKREIS.3DS",
"DT_2ND_FLOOR_BANNKREIS_02.3DS",
"DT_2ND_FLOOR_GEWOELBE.3DS",
"DT_3RD_FLOOR_GEWOELBE.3DS",
"DT_BED_V1.3DS",
"DT_BOOKSHELF_V1.3DS",
"DT_BOOKSHELF_V2.3DS",
"DT_BOOKS_01.3DS",
"DT_CARPET_ROUND_01.3DS",
"DT_CHAINBOX.3DS",
"DT_CRATE_V1.3DS",
"DT_CRATE_V2.3DS",
"DT_FIREPLACE_V1.3DS",
"DT_FIREPLACE_V2.3DS",
"DT_LIGHTER_PENTAGRAMM.3DS",
"DT_SHELF_V1.3DS",
"DT_SKELETON_V01.3DS",
"DT_SKELETON_V01_HEAD.3DS",
"DT_SKELETON_V02.3DS",
"DT_TABLE_01.3DS",
"DT_TABLE_V2.3DS",
"DT_TABLE_V3.3DS",
"DT_TORCH_V1.3DS",
"EVT_CASTEL_FLOOR_1.3DS",
"EVT_CASTEL_FLOOR_2.3DS",
"EVT_CASTEL_FLOOR_3.3DS",
"EVT_CASTEL_FLOOR_4.3DS",
"EVT_CASTEL_FLOOR_5.3DS",
"EVT_CASTEL_PLATE.3DS",
"EVT_CASTLE_HIDDEN_01.3DS",
"EVT_CASTLE_LIFT_01.3DS",
"EVT_CASTLE_LIFT_02.3DS",
"EVT_CASTLE_LIFT_03.3DS",
"EVT_CORNERROOMS_LIFTGATEWALL_01.3DS",
"EVT_CORNERROOMS_LIFT_01.3DS",
"EVT_CORNERROOMS_WHEELWALL_01.3DS",
"EVT_DEMONTOWER_LIFT.3DS",
"EVT_DEMONTOWER_LIFT_SHIELD.3DS",
"EVT_DEMONTOWER_LIFT_WALL.3DS",
"EVT_GATEROOM_WHEEL_01.3DS",
"EVT_GATEROOM_WHEEL_02.3DS",
"EVT_GATE_LARGE_01.3DS",
"EVT_GATE_SMALL_01.3DS",
"EVT_MAINHALL_DOOR_CLAW_LEFT_01.3DS",
"EVT_MAINHALL_DOOR_CLAW_RIGHT_01.3DS",
"EVT_MAINHALL_DOOR_LEFT_01.3DS",
"EVT_MAINHALL_DOOR_LOCK_BL_01.3DS",
"EVT_MAINHALL_DOOR_LOCK_BR_01.3DS",
"EVT_MAINHALL_DOOR_LOCK_TL_01.3DS",
"EVT_MAINHALL_DOOR_LOCK_TR_01.3DS",
"EVT_MAINHALL_DOOR_RIGHT_01.3DS",
"EVT_MAINHALL_PILLAR_01.3DS",
"EVT_MAINHALL_RING_LEFT_01.3DS",
"EVT_MAINHALL_RING_RIGHT_01.3DS",
"EVT_NC_MAINGATE01.3DS",
"EVT_OC_MAINGATE01_01.3DS",
"EVT_OC_MAINGATE01_02.3DS",
"EVT_OC_MAINGATE01_03.3DS",
"EVT_OC_MAINGATE02_01.3DS",
"EVT_OC_MAINGATE02_02.3DS",
"EVT_OC_MAINGATE02_03.3DS",
"EVT_SPAWN_01.3DS",
"EVT_TPL_DECOSTONE_01_DAEMON.3DS",
"EVT_TPL_DECOSTONE_01_DOORS_01.3DS",
"EVT_TPL_DECOSTONE_01_DOORS_02.3DS",
"EVT_TPL_DECOSTONE_01_MUMMY.3DS",
"EVT_TPL_DECOSTONE_01_TARGET.3DS",
"EVT_TPL_GITTERKAEFIG_4X4M.3DS",
"EVT_TPL_GITTERKAEFIG_4X5M.3DS",
"EVT_TPL_METALTHORNS_2X2X05M.3DS",
"EVT_TPL_METALTHORNS_4X4X4M.3DS",
"EVT_TPL_METALTHORNS_DEADLY.3DS",
"EVT_TPL_PILLAR_01.3DS",
"EVT_TPL_STONECEILING_01.3DS",
"EVT_WALLMOVER_01.3DS",
"FAKESCROLL.3DS",
"FMC_BRIDGE_BOTTOM.3DS",
"FMC_BRIDGE_TOP.3DS",
"GROUNDSHADOW.3DS",
"GROUNDSHADOW.3DS",
"HAMMEL.3DS",
"INVISIBLE_CAMERA.3DS",
"INVISIBLE_DEFAULT.3DS",
"INVISIBLE_DRAGVOB.3DS",
"INVISIBLE_KEYFRAME.3DS",
"INVISIBLE_SPCCCAMVOB.3DS",
"INVISIBLE_VOBBOX.3DS",
"INVISIBLE_WAYPOINT.3DS",
"INVISIBLE_ZCCAMTRJ_KEYFRAME.3DS",
"INVISIBLE_ZCCODEMASTER.3DS",
"INVISIBLE_ZCCSCAMERA.3DS",
"INVISIBLE_ZCEARTHQUAKE.3DS",
"INVISIBLE_ZCPFXCONTROLER.3DS",
"INVISIBLE_ZCTRIGGER.3DS",
"INVISIBLE_ZCTRIGGERCHANGELEVEL.3DS",
"INVISIBLE_ZCTRIGGERTELEPORT.3DS",
"INVISIBLE_ZCVOB.3DS",
"INVISIBLE_ZCVOBLIGHT.3DS",
"INVISIBLE_ZCVOBMARKER.3DS",
"INVISIBLE_ZCVOBSCREENFX.3DS",
"INVISIBLE_ZCVOBSOUND.3DS",
"INVISIBLE_ZCVOBSOUNDDAYTIME.3DS",
"INVISIBLE_ZCVOBSPOT.3DS",
"INVISIBLE_ZCVOBSTARTPOINT.3DS",
"INVISIBLE_ZCVOBWAYPOINT.3DS",
"INVISIBLE_ZCZONEMUSIC.3DS",
"INVISIBLE_ZCZONEREVERB.3DS",
"INVISIBLE_ZCZONEZFOG.3DS",
"ITAM_DEX_01.3DS",
"ITAM_DEX_STRG_01.3DS",
"ITAM_HP_01.3DS",
"ITAM_HP_MANA_01.3DS",
"ITAM_MANA_01.3DS",
"ITAM_PROT_EDGE_01.3DS",
"ITAM_PROT_FIRE_01.3DS",
"ITAM_PROT_MAGE_01.3DS",
"ITAM_PROT_POINT_01.3DS",
"ITAM_PROT_TOTAL_01.3DS",
"ITAM_STRG_01.3DS",
"ITAR_BAU_L.3DS",
"ITAR_BAU_M.3DS",
"ITAR_BDT_H.3DS",
"ITAR_BDT_M.3DS",
"ITAR_CORANGAR.3DS",
"ITAR_DIEGO.3DS",
"ITAR_DJG_CRAWLER.3DS",
"ITAR_DJG_H.3DS",
"ITAR_DJG_L.3DS",
"ITAR_DJG_M.3DS",
"ITAR_GOVERNOR.3DS",
"ITAR_KDF_H.3DS",
"ITAR_KDF_L.3DS",
"ITAR_KDW_H.3DS",
"ITAR_LEATHER_L.3DS",
"ITAR_LESTER.3DS",
"ITAR_MIL_L.3DS",
"ITAR_MIL_M.3DS",
"ITAR_NOV_L.3DS",
"ITAR_PAL_H.3DS",
"ITAR_PAL_M.3DS",
"ITAR_PRISONER.3DS",
"ITAR_SLD_H.3DS",
"ITAR_SLD_L.3DS",
"ITAR_SLD_M.3DS",
"ITAR_SMITH.3DS",
"ITAR_TESTDUMMY.3DS",
"ITAR_VLKBABE.3DS",
"ITAR_VLK_H.3DS",
"ITAR_VLK_L.3DS",
"ITAR_VLK_M.3DS",
"ITAR_WIRT.3DS",
"ITAR_XARDAS.3DS",
"ITAT_BUGMANDIBLES.3DS",
"ITAT_CLAW.3DS",
"ITAT_CRAWLERMANDIBLES.3DS",
"ITAT_CRAWLERPLATE.3DS",
"ITAT_DEMONHEART.3DS",
"ITAT_DRAGONBLOOD.3DS",
"ITAT_DRAGONEGG.3DS",
"ITAT_DRAGONSCALE.3DS",
"ITAT_DRGSNAPPERHORN.3DS",
"ITAT_FIREDRAGONHEART.3DS",
"ITAT_FIREGOLEMHEART.3DS",
"ITAT_GOBLINBONE.3DS",
"ITAT_ICEDRAGONHEART.3DS",
"ITAT_ICEGOLEMHEART.3DS",
"ITAT_LURKERCLAW.3DS",
"ITAT_LURKERSKIN.3DS",
"ITAT_MEATBUGFLESH.3DS",
"ITAT_ROCKDRAGONHEART.3DS",
"ITAT_SHADOWFUR.3DS",
"ITAT_SHADOWHORN.3DS",
"ITAT_SHARKSKIN.3DS",
"ITAT_SHARKTEETH.3DS",
"ITAT_SHEEPFUR.3DS",
"ITAT_SKELETONBONE.3DS",
"ITAT_STING.3DS",
"ITAT_STONEGOLEMHEART.3DS",
"ITAT_SWAMPDRAGONHEART.3DS",
"ITAT_TEETH.3DS",
"ITAT_TROLLFUR.3DS",
"ITAT_TROLLTOOTH.3DS",
"ITAT_UNDEADDRAGONSOULSTONE.3DS",
"ITAT_WARANFIRETONGUE.3DS",
"ITAT_WARGFUR.3DS",
"ITAT_WING.3DS",
"ITAT_WOLFFUR.3DS",
"ITFOMUTTON.3DS",
"ITFOMUTTONRAW.3DS",
"ITFO_APPLE.3DS",
"ITFO_BACON.3DS",
"ITFO_BEER.3DS",
"ITFO_BOOZE.3DS",
"ITFO_BREAD.3DS",
"ITFO_CHEESE.3DS",
"ITFO_FISH.3DS",
"ITFO_FISHSOUP.3DS",
"ITFO_HONEY.3DS",
"ITFO_MILK.3DS",
"ITFO_SAUSAGE.3DS",
"ITFO_STEW.3DS",
"ITFO_WATER.3DS",
"ITFO_WINE.3DS",
"ITFO_WINEBERRYS_01.3DS",
"ITKE_KEY_01.3DS",
"ITKE_KEY_02.3DS",
"ITKE_KEY_03.3DS",
"ITKE_LOCKPICK.3DS",
"ITLS_TORCHBURNED_01.3DS",
"ITLS_TORCH_01.3DS",
"ITMISWORDBLADE.3DS",
"ITMISWORDBLADEHOT.3DS",
"ITMISWORDRAW.3DS",
"ITMISWORDRAWHOT.3DS",
"ITMI_AQUAMARINE.3DS",
"ITMI_BROOM.3DS",
"ITMI_BRUSH.3DS",
"ITMI_COAL.3DS",
"ITMI_DARKPEARL.3DS",
"ITMI_FLASK.3DS",
"ITMI_GOLD.3DS",
"ITMI_GOLDCANDLEHOLDER.3DS",
"ITMI_GOLDCHALICE.3DS",
"ITMI_GOLDCHEST.3DS",
"ITMI_GOLDCUP.3DS",
"ITMI_GOLDNECKLACE.3DS",
"ITMI_GOLDPLATE.3DS",
"ITMI_GOLDRING.3DS",
"ITMI_HAMMER.3DS",
"ITMI_HOLYWATER.3DS",
"ITMI_INNOSEYE_BROKEN_MIS.3DS",
"ITMI_INNOSEYE_DISCHARGED_MIS.3DS",
"ITMI_INNOSEYE_MIS.3DS",
"ITMI_INNOSSTATUE.3DS",
"ITMI_JEWELERYCHEST.3DS",
"ITMI_JOINT.3DS",
"ITMI_JOINT_GER.3DS",
"ITMI_JOINT_US.3DS",
"ITMI_LUTE.3DS",
"ITMI_MOLERATLUBRIC.3DS",
"ITMI_NUGGET.3DS",
"ITMI_OLDCOIN.3DS",
"ITMI_PACKET.3DS",
"ITMI_PAN.3DS",
"ITMI_PANFULL.3DS",
"ITMI_PITCH.3DS",
"ITMI_PLIERS.3DS",
"ITMI_POCKET.3DS",
"ITMI_QUARTZ.3DS",
"ITMI_RAKE.3DS",
"ITMI_RING_01.3DS",
"ITMI_RING_01.3DS",
"ITMI_ROCKCRYSTAL.3DS",
"ITMI_RUNEBLANK.3DS",
"ITMI_SAW.3DS",
"ITMI_SCOOP.3DS",
"ITMI_SEXTANT.3DS",
"ITMI_SILVERCANDLEHOLDER.3DS",
"ITMI_SILVERCHALICE.3DS",
"ITMI_SILVERCUP.3DS",
"ITMI_SILVERNECKLACE.3DS",
"ITMI_SILVERPLATE.3DS",
"ITMI_SILVERRING.3DS",
"ITMI_STOMPER.3DS",
"ITMI_STONEOFKNOWLEGDE_MIS.3DS",
"ITMI_SULFUR.3DS",
"ITMW_005_1H_DAGGER_01.3DS",
"ITMW_005_1H_POKER_01.3DS",
"ITMW_007_1H_SICKLE_01.3DS",
"ITMW_008_1H_MACE_LIGHT_01.3DS",
"ITMW_008_1H_POLE_01.3DS",
"ITMW_010_1H_CLUB_01.3DS",
"ITMW_010_1H_SLEDGEHAMMER_01.3DS",
"ITMW_010_1H_SWORD_SHORT_01.3DS",
"ITMW_010_1H_VLK_HATCHET_01.3DS",
"ITMW_012_1H_KNIFE_02.3DS",
"ITMW_012_1H_NAILMACE_01.3DS",
"ITMW_012_1H_SCYTHE_01.3DS",
"ITMW_012_1H_SWORD_SHORT_02.3DS",
"ITMW_016_1H_SWORD_SHORT_03.3DS",
"ITMW_018_1H_MACE_01.3DS",
"ITMW_018_1H_SWORDCANE_01.3DS",
"ITMW_020_1H_SWORD_OLD_01.3DS",
"ITMW_020_1H_SWORD_SHORT_04.3DS",
"ITMW_020_2H_AXE_LUMBERJACK_01.3DS",
"ITMW_020_2H_NOV_STAFF_01.3DS",
"ITMW_020_2H_PICKAXE_01.3DS",
"ITMW_022_1H_MACE_WAR_01.3DS",
"ITMW_025_1H_MIL_SWORD_BROAD_01.3DS",
"ITMW_025_1H_SLD_AXE_01.3DS",
"ITMW_025_1H_SLD_SWORD_01.3DS",
"ITMW_025_1H_SWORD_SHORT_05.3DS",
"ITMW_025_2H_MISC_AXE_OLD_01.3DS",
"ITMW_025_2H_STAFF_02.3DS",
"ITMW_025_2H_SWORD_OLD_01.3DS",
"ITMW_028_1H_MACE_02.3DS",
"ITMW_028_1H_WARHAMMER_01.3DS",
"ITMW_028_2H_HALBERD_01.3DS",
"ITMW_030_1H_AXE_01.3DS",
"ITMW_030_1H_COMMON_SWORD_01.3DS",
"ITMW_030_1H_PAL_SWORD_02.3DS",
"ITMW_030_1H_PAL_SWORD_BASTARD_RAW_01.3DS",
"ITMW_030_1H_SWORD_03.3DS",
"ITMW_030_1H_SWORD_LONG_01.3DS",
"ITMW_030_2H_KDF_HAMMER_01.3DS",
"ITMW_032_2H_STAFF_03.3DS",
"ITMW_032_2H_SWORD_LIGHT_01.3DS",
"ITMW_035_1H_MACE_03.3DS",
"ITMW_035_1H_MACE_WAR_02.3DS",
"ITMW_035_1H_SWORD_04.3DS",
"ITMW_035_2H_AXE_LIGHT_03.3DS",
"ITMW_035_2H_SLD_AXE_01.3DS",
"ITMW_035_2H_SLD_SWORD_01.3DS",
"ITMW_037_1H_SWORD_LONG_02.3DS",
"ITMW_040_1H_AXE_02.3DS",
"ITMW_040_1H_AXE_03.3DS",
"ITMW_040_2H_PAL_SWORD_03.3DS",
"ITMW_040_2H_PAL_SWORD_HEAVY_RAW_01.3DS",
"ITMW_045_1H_MACE_04.3DS",
"ITMW_045_1H_SWORD_BASTARD_01.3DS",
"ITMW_045_1H_SWORD_LONG_04.3DS",
"ITMW_045_1H_SWORD_SMITH_02.3DS",
"ITMW_050_1H_MACE_WAR_03.3DS",
"ITMW_050_1H_SWORD_05.3DS",
"ITMW_050_1H_SWORD_RAPIER_01.3DS",
"ITMW_050_2H_SWORD_SMITH_02.3DS",
"ITMW_055_1H_SWORD_LONG_05.3DS",
"ITMW_055_2H_SWORD_LIGHT_05.3DS",
"ITMW_058_1H_SWORD_BASTARD_02.3DS",
"ITMW_058_1H_WARHAMMER_02.3DS",
"ITMW_060_1H_MACE_WAR_04.3DS",
"ITMW_060_1H_SWORD_SMITH_03.3DS",
"ITMW_060_2H_AXE_HEAVY_01.3DS",
"ITMW_060_2H_SWORD_01.3DS",
"ITMW_065_1H_SWORDCANE_02.3DS",
"ITMW_065_1H_SWORD_BASTARD_03.3DS",
"ITMW_065_1H_SWORD_BASTARD_04.3DS",
"ITMW_065_1H_WARHAMMER_03.3DS",
"ITMW_065_2H_GREATAXE_01.3DS",
"ITMW_068_2H_SWORD_02.3DS",
"ITMW_070_2H_AXE_HEAVY_03.3DS",
"ITMW_070_2H_SWORD_09.3DS",
"ITMW_070_2H_SWORD_SMITH_03.3DS",
"ITMW_075_1H_SWORD_SMITH_04.3DS",
"ITMW_075_2H_AXE_HEAVY_04.3DS",
"ITMW_075_2H_SWORD_HEAVY_03.3DS",
"ITMW_080_2H_AXE_HEAVY_02.3DS",
"ITMW_080_2H_SWORD_HEAVY_04.3DS",
"ITMW_090_1H_SWORD_SMITH_05.3DS",
"ITMW_090_2H_SWORD_SMITH_04.3DS",
"ITMW_110_2H_SWORD_SMITH_05.3DS",
"ITMW_2H_ORCAXE_01.3DS",
"ITMW_2H_ORCAXE_02.3DS",
"ITMW_2H_ORCAXE_03.3DS",
"ITMW_2H_ORCAXE_04.3DS",
"ITMW_2H_ORCMACE_01.3DS",
"ITMW_2H_ORCSWORD_01.3DS",
"ITMW_2H_ORCSWORD_02.3DS",
"ITPL_BEET.3DS",
"ITPL_BLUEPLANT.3DS",
"ITPL_DEX_HERB_01.3DS",
"ITPL_FORESTBERRY.3DS",
"ITPL_HEALTH_HERB_01.3DS",
"ITPL_HEALTH_HERB_02.3DS",
"ITPL_HEALTH_HERB_03.3DS",
"ITPL_MANA_HERB_01.3DS",
"ITPL_MANA_HERB_02.3DS",
"ITPL_MANA_HERB_03.3DS",
"ITPL_MUSHROOM_01.3DS",
"ITPL_MUSHROOM_02.3DS",
"ITPL_PERM_HERB.3DS",
"ITPL_PLANEBERRY.3DS",
"ITPL_SPEED_HERB_01.3DS",
"ITPL_STRENGTH_HERB_01.3DS",
"ITPL_SWAMPHERB.3DS",
"ITPL_TEMP_HERB.3DS",
"ITPL_WEED.3DS",
"ITPO_HEALTH_01.3DS",
"ITPO_HEALTH_02.3DS",
"ITPO_HEALTH_03.3DS",
"ITPO_MANA_01.3DS",
"ITPO_MANA_02.3DS",
"ITPO_MANA_03.3DS",
"ITPO_PERM_DEX.3DS",
"ITPO_PERM_HEALTH.3DS",
"ITPO_PERM_MANA.3DS",
"ITPO_PERM_STR.3DS",
"ITPO_SPEED.3DS",
"ITRI_DEX_01.3DS",
"ITRI_DEX_02.3DS",
"ITRI_DEX_STRG_01.3DS",
"ITRI_HP_01.3DS",
"ITRI_HP_02.3DS",
"ITRI_HP_MANA_01.3DS",
"ITRI_MANA_01.3DS",
"ITRI_MANA_02.3DS",
"ITRI_PROT_EDGE_01.3DS",
"ITRI_PROT_EDGE_02.3DS",
"ITRI_PROT_FIRE_01.3DS",
"ITRI_PROT_FIRE_02.3DS",
"ITRI_PROT_MAGE_01.3DS",
"ITRI_PROT_MAGE_02.3DS",
"ITRI_PROT_POINT_01.3DS",
"ITRI_PROT_POINT_02.3DS",
"ITRI_PROT_TOTAL_01.3DS",
"ITRI_PROT_TOTAL_02.3DS",
"ITRI_STR_01.3DS",
"ITRI_STR_02.3DS",
"ITRU_ARMYOFDARKNESS.3DS",
"ITRU_BREATHOFDEATH.3DS",
"ITRU_CHARGEFIREBALL.3DS",
"ITRU_FEAR.3DS",
"ITRU_FIREBOLT.3DS",
"ITRU_FIRERAIN.3DS",
"ITRU_FIRESTORM.3DS",
"ITRU_FULLHEAL.3DS",
"ITRU_HARMUNDEAD.3DS",
"ITRU_ICEBOLT.3DS",
"ITRU_ICECUBE.3DS",
"ITRU_ICEWAVE.3DS",
"ITRU_INSTANTFIREBALL.3DS",
"ITRU_LIGHT.3DS",
"ITRU_LIGHTHEAL.3DS",
"ITRU_LIGHTNINGFLASH.3DS",
"ITRU_MASSDEATH.3DS",
"ITRU_MASTEROFDESASTER.3DS",
"ITRU_MEDIUMHEAL.3DS",
"ITRU_PALDESTROYEVIL.3DS",
"ITRU_PALFULLHEAL.3DS",
"ITRU_PALHOLYBOLT.3DS",
"ITRU_PALLIGHT.3DS",
"ITRU_PALLIGHTHEAL.3DS",
"ITRU_PALMEDIUMHEAL.3DS",
"ITRU_PALREPELEVIL.3DS",
"ITRU_PALTELEPORTSECRET.3DS",
"ITRU_PYROKINESIS.3DS",
"ITRU_SHRINK.3DS",
"ITRU_SLEEP.3DS",
"ITRU_SUMDEMON.3DS",
"ITRU_SUMGOBSKEL.3DS",
"ITRU_SUMGOL.3DS",
"ITRU_SUMSKEL.3DS",
"ITRU_SUMWOLF.3DS",
"ITRU_TELEPORTFARM.3DS",
"ITRU_TELEPORTMONASTERY.3DS",
"ITRU_TELEPORTOC.3DS",
"ITRU_TELEPORTOWDEMONTOWER.3DS",
"ITRU_TELEPORTPASSNW.3DS",
"ITRU_TELEPORTPASSOW.3DS",
"ITRU_TELEPORTSEAPORT.3DS",
"ITRU_TELEPORTXARDAS.3DS",
"ITRU_TELEPORT_2.3DS",
"ITRU_TELEPORT_3.3DS",
"ITRU_THUNDERBALL.3DS",
"ITRU_WINDFIST.3DS",
"ITRU_ZAP.3DS",
"ITRW_ARROW.3DS",
"ITRW_BOLT.3DS",
"ITSC_ARMYOFDARKNESS.3DS",
"ITSC_BREATHOFDEATH.3DS",
"ITSC_CHARGEFIREBALL.3DS",
"ITSC_FEAR.3DS",
"ITSC_FIREBOLT.3DS",
"ITSC_FIRERAIN.3DS",
"ITSC_FIRESTORM.3DS",
"ITSC_FULLHEAL.3DS",
"ITSC_HARMUNDEAD.3DS",
"ITSC_ICEBOLT.3DS",
"ITSC_ICECUBE.3DS",
"ITSC_ICEWAVE.3DS",
"ITSC_INSTANTFIREBALL.3DS",
"ITSC_LIGHT.3DS",
"ITSC_LIGHTHEAL.3DS",
"ITSC_LIGHTNINGFLASH.3DS",
"ITSC_MASSDEATH.3DS",
"ITSC_MEDIUMHEAL.3DS",
"ITSC_PALDESTROYEVIL.3DS",
"ITSC_PALFULLHEAL.3DS",
"ITSC_PALHOLYBOLT.3DS",
"ITSC_PALLIGHT.3DS",
"ITSC_PALLIGHTHEAL.3DS",
"ITSC_PALMEDIUMHEAL.3DS",
"ITSC_PALREPELEVIL.3DS",
"ITSC_PYROKINESIS.3DS",
"ITSC_SHRINK.3DS",
"ITSC_SLEEP.3DS",
"ITSC_SUMDEMON.3DS",
"ITSC_SUMGOBSKEL.3DS",
"ITSC_SUMGOL.3DS",
"ITSC_SUMSKEL.3DS",
"ITSC_SUMWOLF.3DS",
"ITSC_THUNDERBALL.3DS",
"ITSC_TRFDRAGONSNAPPER.3DS",
"ITSC_TRFFIREWARAN.3DS",
"ITSC_TRFGIANTBUG.3DS",
"ITSC_TRFGIANTRAT.3DS",
"ITSC_TRFLURKER.3DS",
"ITSC_TRFSCAVENGER.3DS",
"ITSC_TRFSHADOWBEAST.3DS",
"ITSC_TRFSHEEP.3DS",
"ITSC_TRFSNAPPER.3DS",
"ITSC_TRFWARAN.3DS",
"ITSC_TRFWARG.3DS",
"ITSC_TRFWOLF.3DS",
"ITSC_WINDFIST.3DS",
"ITSC_ZAP.3DS",
"ITWR_BOOK_01.3DS",
"ITWR_BOOK_02_01.3DS",
"ITWR_BOOK_02_02.3DS",
"ITWR_BOOK_02_03.3DS",
"ITWR_BOOK_02_04.3DS",
"ITWR_BOOK_02_05.3DS",
"ITWR_MAP_01.3DS",
"ITWR_SCROLL_01.3DS",
"ITWR_SCROLL_02.3DS",
"LIGHT.3DS",
"MAGICFRONTIER_OUT.3DS",
"MAGICFRONTIER_OUT.3DS",
"MARKER.3DS",
"MFX_FEAR4.3DS",
"MFX_FEAR4.3DS",
"MIN_COB_STONE_V1_10.3DS",
"MIN_COB_STONE_V2_10.3DS",
"MIN_COB_STONE_V3_10.3DS",
"MIN_LOB_BRIDGERAMP.3DS",
"MIN_LOB_BRIDGESTAND.3DS",
"MIN_LOB_BRIDGESTAND_02.3DS",
"MIN_LOB_BRIDGE_30M.3DS",
"MIN_LOB_BRIDGE_4X4M.3DS",
"MIN_LOB_BRIDGE_ANGEL_4M.3DS",
"MIN_LOB_COUPLESTONES.3DS",
"MIN_LOB_COVER_4X7M.3DS",
"MIN_LOB_HANDRAIL_1.3DS",
"MIN_LOB_HANDRAIL_2.3DS",
"MIN_LOB_HANDRAIL_3.3DS",
"MIN_LOB_MELTER.3DS",
"MIN_LOB_PLANKS_2X3M.3DS",
"MIN_LOB_PLANKS_2X4M.3DS",
"MIN_LOB_PLANKS_2X5M.3DS",
"MIN_LOB_PLANKS_3X11M.3DS",
"MIN_LOB_PLANKS_3X7M.3DS",
"MIN_LOB_SOLDIERSHUT.3DS",
"MIN_LOB_STANDINGWORKPLANK_5X7M.3DS",
"MIN_LOB_STOMPERSTAND.3DS",
"MIN_LOB_STONE_V1_30.3DS",
"MIN_LOB_STONE_V2_30.3DS",
"MIN_LOB_STONE_V3_30.3DS",
"MIN_LOB_STONE_V3_40.3DS",
"MIN_LOB_STONE_V3_50.3DS",
"MIN_LOB_WINKELSTEG.3DS",
"MIN_LOB_WORKPLANK_4X6M.3DS",
"MIN_LOB_WORKPLANK_5X7M.3DS",
"MIN_MOB_STONE_V1_20.3DS",
"MIN_MOB_STONE_V2_20.3DS",
"MIN_MOB_STONE_V3_20.3DS",
"MIN_ORE_BIG_V1.3DS",
"MIN_ORE_BIG_V2.3DS",
"NC_BIRDFRIGHTENER.3DS",
"NC_LOB_BAR_TABLE1.3DS",
"NC_LOB_HOUSEPLANKS.3DS",
"NC_LOB_LIGHTER.3DS",
"NC_LOB_LOG1.3DS",
"NC_LOB_LOG2.3DS",
"NC_LOB_LOG3.3DS",
"NC_LOB_NICE.3DS",
"NC_LOB_NICE2.3DS",
"NC_LOB_TABLE1.3DS",
"NC_LOB_TABLE2.3DS",
"NC_OREHEAP.3DS",
"NC_OREHEAP_FENCE.3DS",
"NC_OREHEAP_PFX.3DS",
"NC_OREHEAP_PFX.3DS",
"NC_PLANKS_V01.3DS",
"NC_STAIRS_V01.3DS",
"NW_ABANDONEDMINE_BETA.3DS",
"NW_CAVEWEBS_V201.3DS",
"NW_CITY_BEAMS_01.3DS",
"NW_CITY_BEAMS_02.3DS",
"NW_CITY_BEAMS_BOWS_01.3DS",
"NW_CITY_BEAMS_FARM_01.3DS",
"NW_CITY_BEAMS_FARM_02.3DS",
"NW_CITY_BEAMS_MIXSHOP_01.3DS",
"NW_CITY_BEAMS_PUB_01.3DS",
"NW_CITY_BEAMS_SMITH_01.3DS",
"NW_CITY_BEAM_01.3DS",
"NW_CITY_BOOKSHELF_01.3DS",
"NW_CITY_CANDLE_01.3DS",
"NW_CITY_CARPET_01.3DS",
"NW_CITY_CARPET_02.3DS",
"NW_CITY_CARPET_03.3DS",
"NW_CITY_CART_01.3DS",
"NW_CITY_COUNTER_01.3DS",
"NW_CITY_CUPBOARD_POOR_01.3DS",
"NW_CITY_CUPBOARD_POOR_02.3DS",
"NW_CITY_CUPBOARD_RICH_01.3DS",
"NW_CITY_CUPBOARD_RICH_02.3DS",
"NW_CITY_DECO_PICTURE_01.3DS",
"NW_CITY_DECO_PICTURE_02.3DS",
"NW_CITY_DECO_SHADOWHEAD_01.3DS",
"NW_CITY_DECO_SHIELD_01.3DS",
"NW_CITY_DECO_SHIELD_02.3DS",
"NW_CITY_DECO_SWORDFISH_01.3DS",
"NW_CITY_DECO_TROLLHEAD_01.3DS",
"NW_CITY_DECO_WHEEL_01.3DS",
"NW_CITY_DECO_WOLFHEAD_01.3DS",
"NW_CITY_FIREPLACE_LARGE_01.3DS",
"NW_CITY_FIREPLACE_LARGE_011.3DS",
"NW_CITY_FIREPLACE_LARGE_02.3DS",
"NW_CITY_FIREPLACE_LARGE_021.3DS",
"NW_CITY_FIREPLACE_NORMAL_01.3DS",
"NW_CITY_FIREPLACE_NORMAL_011.3DS",
"NW_CITY_FLOWERPOT_01.3DS",
"NW_CITY_GALLOWS_01.3DS",
"NW_CITY_HIDDENDOOR_01.3DS",
"NW_CITY_KNIGHT_ARMOR_01.3DS",
"NW_CITY_KNIGHT_STATUE_01.3DS",
"NW_CITY_MAP_WAR_CLOSED_01.3DS",
"NW_CITY_MAP_WAR_OPEN_01.3DS",
"NW_CITY_MARKETSTALL_ALCHEMY_01.3DS",
"NW_CITY_MARKETSTALL_FOOD_01.3DS",
"NW_CITY_MARKETSTALL_JUNKSHOP_01.3DS",
"NW_CITY_MARKETSTALL_ROOF_01.3DS",
"NW_CITY_MARKETSTALL_WEAPONS_01.3DS",
"NW_CITY_OILLAMP_01.3DS",
"NW_CITY_SHIP_01.3DS",
"NW_CITY_SIGN_BOWS_01.3DS",
"NW_CITY_SIGN_HOTEL_01.3DS",
"NW_CITY_SIGN_MIXSHOP_01.3DS",
"NW_CITY_SIGN_PUB_01.3DS",
"NW_CITY_SIGN_SMITH_01.3DS",
"NW_CITY_STREETLAMP_01.3DS",
"NW_CITY_TABLE_NORMAL_01.3DS",
"NW_CITY_TABLE_PEASANT_01.3DS",
"NW_CITY_TABLE_PEASANT_02.3DS",
"NW_CITY_TABLE_RICH_01.3DS",
"NW_CITY_TABLE_RICH_02.3DS",
"NW_CITY_TABLE_WAR_01.3DS",
"NW_CITY_VLIES_01.3DS",
"NW_CITY_WEAPON_BAG_01.3DS",
"NW_CITY_WEAPON_BARREL_01.3DS",
"NW_CITY_WINDOW_STONE_OUT_01.3DS",
"NW_CITY_WINDOW_WOOD_IN_01.3DS",
"NW_CITY_WINDOW_WOOD_IN_02.3DS",
"NW_CITY_WINDOW_WOOD_OUT_01.3DS",
"NW_DRAGONISLE_BIGBRIDGE_01.3DS",
"NW_DRAGONISLE_BIGDOOR_HEAD_LEFT_01.3DS",
"NW_DRAGONISLE_BIGDOOR_HEAD_RIGHT_01.3DS",
"NW_DRAGONISLE_BIGDOOR_LEFT_01.3DS",
"NW_DRAGONISLE_BIGDOOR_RIGHT_01.3DS",
"NW_DRAGONISLE_INVISIBLEORCWALL_01.3DS",
"NW_DRAGONISLE_STAIRSALPHA_01.3DS",
"NW_DRAGONISLE_STALAGTITE_01.3DS",
"NW_DRAGONISLE_STALAGTITE_02.3DS",
"NW_DRAGONISLE_STALAGTITE_03.3DS",
"NW_DRAGONISLE_STALAGTITE_04.3DS",
"NW_DRAGONISLE_TORTURE_01.3DS",
"NW_DRAGONISLE_TORTURE_02.3DS",
"NW_DRAGONISLE_TORTURE_03.3DS",
"NW_DRAGONISLE_TORTURE_04.3DS",
"NW_DRAGONISLE_TORTURE_05.3DS",
"NW_EVT_CEMENTARYCOFFIN_01.3DS",
"NW_EVT_CEMENTARYSTEP_01.3DS",
"NW_EVT_MONASTERYWALL_01.3DS",
"NW_HARBOUR_ANCHOR_01.3DS",
"NW_HARBOUR_BARRELGROUP_01.3DS",
"NW_HARBOUR_BARRELGROUP_02.3DS",
"NW_HARBOUR_BARREL_01.3DS",
"NW_HARBOUR_CANONBALLS_01.3DS",
"NW_HARBOUR_CANONBALLS_02.3DS",
"NW_HARBOUR_CANON_01.3DS",
"NW_HARBOUR_CRATEBROKEN_01.3DS",
"NW_HARBOUR_CRATEPILE_01.3DS",
"NW_HARBOUR_CRATE_01.3DS",
"NW_HARBOUR_FISHINGNETBIG.3DS",
"NW_HARBOUR_FISHINGNETSMALL.3DS",
"NW_HARBOUR_FISHINGNET_01.3DS",
"NW_HARBOUR_IRONROPEHOLDER_01.3DS",
"NW_HARBOUR_IRONROPEHOLDER_WROPE_01.3DS",
"NW_HARBOUR_RINGBIG_01.3DS",
"NW_HARBOUR_RINGSMALL_01.3DS",
"NW_HARBOUR_ROPE_01.3DS",
"NW_HARBOUR_SMALL_BOAT_01.3DS",
"NW_HARBOUR_SMALL_BOAT_02.3DS",
"NW_HARBOUR_SMALL_BOAT_03.3DS",
"NW_MISC_BIG_TENT_430P.3DS",
"NW_MISC_BOARDS_01A.3DS",
"NW_MISC_BOARDS_01B.3DS",
"NW_MISC_BOARDS_01C.3DS",
"NW_MISC_BOARDS_02A.3DS",
"NW_MISC_BOARDS_02B.3DS",
"NW_MISC_BOARDS_02C.3DS",
"NW_MISC_CAVE_BOARDING_01.3DS",
"NW_MISC_CHAIN_01.3DS",
"NW_MISC_DECO_INNOS_LARGE_01.3DS",
"NW_MISC_DUMPTRUCK_01.3DS",
"NW_MISC_FIELDGRAVE_01.3DS",
"NW_MISC_FIREPLACE_01.3DS",
"NW_MISC_GRAVESTONE_01.3DS",
"NW_MISC_GRAVESTONE_02.3DS",
"NW_MISC_HANGROPE.3DS",
"NW_MISC_HARPIE_STANDY.3DS",
"NW_MISC_HUMAN_STANDY.3DS",
"NW_MISC_INNOS_GROUND_01.3DS",
"NW_MISC_MINE_ENTRANCE_01.3DS",
"NW_MISC_POOR_HUT_01.3DS",
"NW_MISC_SIGN_01.3DS",
"NW_MISC_SKELETON_01.3DS",
"NW_MISC_SKELETON_02.3DS",
"NW_MISC_SKELETON_03.3DS",
"NW_MISC_SKELETON_04.3DS",
"NW_MISC_SPIDERWEBS_01.3DS",
"NW_MISC_STRAW_01.3DS",
"NW_MISC_STRAW_02.3DS",
"NW_MISC_STRAW_GROUP_01.3DS",
"NW_MISC_TREASURE_01.3DS",
"NW_MISC_WINDMILL_ROTOR_01.3DS",
"NW_MONASTERY_ALTAR_01.3DS",
"NW_NATURE_BAUMSTAMM_01_30P.3DS",
"NW_NATURE_BAUMSTAMM_166P.3DS",
"NW_NATURE_BAUMSTUMPF_02_115P.3DS",
"NW_NATURE_BAUMSTUMPF_02_154P.3DS",
"NW_NATURE_BAUMSTUMPF_03_174P.3DS",
"NW_NATURE_BAUMSTUMPF_115P.3DS",
"NW_NATURE_BAUMSTUMPF_154P.3DS",
"NW_NATURE_BIGTREE_356P.3DS",
"NW_NATURE_BIGTREE_SUNNY_356P.3DS",
"NW_NATURE_BUSH_01.3DS",
"NW_NATURE_BUSH_120P.3DS",
"NW_NATURE_BUSH_25P.3DS",
"NW_NATURE_BUSH_300P.3DS",
"NW_NATURE_BUSH_56P.3DS",
"NW_NATURE_BUSH_60P.3DS",
"NW_NATURE_DUCKWEED_144P.3DS",
"NW_NATURE_DUCKWEED_72P.3DS",
"NW_NATURE_FARNTEPPICH_306P.3DS",
"NW_NATURE_FARNTEPPICH_612P.3DS",
"NW_NATURE_FARN_102P.3DS",
"NW_NATURE_FARN_BIG_01.3DS",
"NW_NATURE_FARN_SMALL_102P.3DS",
"NW_NATURE_FENCE_01.3DS",
"NW_NATURE_GRASSGROUP_01.3DS",
"NW_NATURE_GREAT_WEED_XGROUP.3DS",
"NW_NATURE_HANGPLANTS_01.3DS",
"NW_NATURE_HANGPLANTS_02.3DS",
"NW_NATURE_HOHETANNEN_01_531P.3DS",
"NW_NATURE_HOHETANNEN_02_531P.3DS",
"NW_NATURE_HOHETANNE_59P.3DS",
"NW_NATURE_HOHETANNE_91P.3DS",
"NW_NATURE_HOHETANNE_MIDDLE_59P.3DS",
"NW_NATURE_HOHETANNE_VERYHIGH_59P.3DS",
"NW_NATURE_LIANA_01_400P.3DS",
"NW_NATURE_LIANA_01_87P.3DS",
"NW_NATURE_LONG_BUSH_360P.3DS",
"NW_NATURE_PLANT_01.3DS",
"NW_NATURE_PLANT_02.3DS",
"NW_NATURE_PLANT_03.3DS",
"NW_NATURE_SIDEPLANT_01.3DS",
"NW_NATURE_SIDEPLANT_BIG_01.3DS",
"NW_NATURE_SIDEPLANT_CORNER_01.3DS",
"NW_NATURE_SMALLTREE_103P.3DS",
"NW_NATURE_SMALLTREE_79P.3DS",
"NW_NATURE_SMALLWEED_24P.3DS",
"NW_NATURE_SMALL_ROOTS_30P.3DS",
"NW_NATURE_STONE_BIGFLAT_01.3DS",
"NW_NATURE_STONE_BIGFLAT_02.3DS",
"NW_NATURE_STONE_BIGHIGH_01.3DS",
"NW_NATURE_STONE_BIGHIGH_02.3DS",
"NW_NATURE_STONE_CULT_ALTAR_01.3DS",
"NW_NATURE_STONE_CULT_PART_01.3DS",
"NW_NATURE_STONE_CULT_PART_02.3DS",
"NW_NATURE_STONE_CULT_PART_03.3DS",
"NW_NATURE_STONE_CULT_SCENE_01.3DS",
"NW_NATURE_STONE_CULT_STAND_01.3DS",
"NW_NATURE_STONE_CULT_STAND_02.3DS",
"NW_NATURE_STONE_CULT_TOP_01.3DS",
"NW_NATURE_STONE_CULT_TOP_02.3DS",
"NW_NATURE_STONE_MANYSTONES_01.3DS",
"NW_NATURE_TANNE_100P.3DS",
"NW_NATURE_TANNE_75P.3DS",
"NW_NATURE_WATERGRASS_02_100P.3DS",
"NW_NATURE_WATERGRASS_56P.3DS",
"NW_NATURE_WATERLILI_RED_32P.3DS",
"NW_NATURE_WATERLILI_WHITE_32P.3DS",
"NW_NATURE_WATERLILI_WHITE_64P.3DS",
"NW_NATURE_WOODPIECE_01.3DS",
"NW_ORETRAIL_BETA.3DS",
"NW_SHIP_STAIRS_AND_MASTS_01.3DS",
"NW_SHIP_STAIRS_NAVROOM_01.3DS",
"OC_BARONSLEDGE_V1.3DS",
"OC_BARRELHOLDER_V01.3DS",
"OC_BARRELS_REIHE.3DS",
"OC_BARRELS_STRUBBELIG.3DS",
"OC_BARREL_V1.3DS",
"OC_BARREL_V1_DESTROYED.3DS",
"OC_BARREL_V2.3DS",
"OC_BARREL_V2_DESTROYED.3DS",
"OC_BIGLIGHTER_01.3DS",
"OC_CHICKENSTICK_CHICKEN_V01.3DS",
"OC_CHICKENSTICK_V01.3DS",
"OC_CHICKENSTICK_V02.3DS",
"OC_CHIMNEY_V1.3DS",
"OC_CHIMNEY_V2.3DS",
"OC_DECORATE_V1.3DS",
"OC_DECORATE_V2.3DS",
"OC_DECORATE_V3.3DS",
"OC_DECORATE_V4.3DS",
"OC_DECORATE_V5.3DS",
"OC_DECOROOF_V1.3DS",
"OC_DECOROOF_V2.3DS",
"OC_DECOWALL_01.3DS",
"OC_DECOWALL_02.3DS",
"OC_DUNGEON_PLANKS.3DS",
"OC_EBA_FURE_SMALL_V1.3DS",
"OC_EBA_FURE_SMALL_V2.3DS",
"OC_EBA_FURE_SMALL_V3.3DS",
"OC_EBA_FUR_V1.3DS",
"OC_FIREPLACEBIG_V01.3DS",
"OC_FIREPLACEBIG_V01_CHICKEN_V01.3DS",
"OC_FIREPLACE_V1.3DS",
"OC_FIREPLACE_V2.3DS",
"OC_FIREPLACE_V3.3DS",
"OC_FIREPLACE_V5.3DS",
"OC_FIREWOOD_V1.3DS",
"OC_FIREWOOD_V2.3DS",
"OC_FIREWOOD_V3.3DS",
"OC_GARBAGE_V1.3DS",
"OC_GATE_KITCHEN.3DS",
"OC_GATE_WELL.3DS",
"OC_KITCHENSTUFF_V01.3DS",
"OC_LEATHERSTAND_V01.3DS",
"OC_LOB_BOWTRAIN.3DS",
"OC_LOB_CAGE.3DS",
"OC_LOB_CAGE2.3DS",
"OC_LOB_CHAIN.3DS",
"OC_LOB_CHAIN_ALONE.3DS",
"OC_LOB_FIREPLACE_HUGE.3DS",
"OC_LOB_FLAG_SMALL.3DS",
"OC_LOB_GALGEN.3DS",
"OC_LOB_GALGEN_V2.3DS",
"OC_LOB_GATE_BIG.3DS",
"OC_LOB_GATE_SMALL.3DS",
"OC_LOB_GATE_SMALL2.3DS",
"OC_LOB_GATE_SMALL3.3DS",
"OC_LOB_LIGHTER_HUGE3.3DS",
"OC_LOB_PLANKBROKEN_SMALL.3DS",
"OC_LOB_PLANKBROKEN_SMALL2.3DS",
"OC_LOB_PLANK_INDOOR.3DS",
"OC_LOB_PLANK_INDOOR_BIG.3DS",
"OC_LOB_PLANK_INDOOR_LARGE.3DS",
"OC_LOB_SHELF_1.3DS",
"OC_LOB_STAIRS_02.3DS",
"OC_LOB_STAIRS_03.3DS",
"OC_LOB_STAIRS_05.3DS",
"OC_LOB_STAIRS_10.3DS",
"OC_LOB_STAIRS_ROUND.3DS",
"OC_LOB_STONE.3DS",
"OC_LOB_STONEBROKEN.3DS",
"OC_LOB_TABLE_EBA.3DS",
"OC_LOB_TABLE_HEAVY.3DS",
"OC_LOB_TABLE_HEAVY_LONG.3DS",
"OC_LOB_TORCHHOLDER_FILLED.3DS",
"OC_LOB_WASTER.3DS",
"OC_MOB_BRAKER.3DS",
"OC_MOB_DESK.3DS",
"OC_MOB_SHELVES_BIG.3DS",
"OC_MOB_SHELVES_MEDIUM.3DS",
"OC_MOB_SHELVES_SMALL.3DS",
"OC_MOB_TABLE_NORMAL_DEFECT.3DS",
"OC_OLDSAWHOUSE_V1.3DS",
"OC_PICTURE_V1.3DS",
"OC_PICTURE_V2.3DS",
"OC_SACK_V01.3DS",
"OC_SACK_V02.3DS",
"OC_SACK_V03.3DS",
"OC_SAECKE_01.3DS",
"OC_SAECKE_02.3DS",
"OC_SHELF_V1.3DS",
"OC_SHELF_V2.3DS",
"OC_SHELF_V3.3DS",
"OC_SHELF_V4.3DS",
"OC_STABLE_PLANKS.3DS",
"OC_STAIRS_V01.3DS",
"OC_TABLE_V1.3DS",
"OC_TABLE_V1_DESTROYED.3DS",
"OC_TABLE_V2.3DS",
"OC_TABLE_V2_DESTROYED.3DS",
"OC_TABLE_V3.3DS",
"OC_THRONE_GROUND.3DS",
"OC_WEAPON_ARMORHOLDER.3DS",
"OC_WEAPON_ARMORSHOES.3DS",
"OC_WEAPON_SHELF_EMPTY_V1.3DS",
"OC_WEAPON_SHELF_EMPTY_V2.3DS",
"OC_WEAPON_SHELF_NEW_V1.3DS",
"OC_WEAPON_SHELF_NEW_V2.3DS",
"OC_WEAPON_SHELF_OLD_V1.3DS",
"OC_WEAPON_SHELF_OLD_V2.3DS",
"OC_WEAPON_WALLARMOR.3DS",
"OC_WELL_V1.3DS",
"OM_OREBOX_01.3DS",
"OM_OREHEAP_SMALL_01.3DS",
"OM_ORETABLE.3DS",
};

local ObjectlistLn={
"ITAM_DEX_01.3DS",
"ITAM_DEX_STRG_01.3DS",
"ITAM_HP_01.3DS",
"ITAM_HP_MANA_01.3DS",
"ITAM_MANA_01.3DS",
"ITAM_PROT_EDGE_01.3DS",
"ITAM_PROT_FIRE_01.3DS",
"ITAM_PROT_MAGE_01.3DS",
"ITAM_PROT_POINT_01.3DS",
"ITAM_PROT_TOTAL_01.3DS",
"ITAM_STRG_01.3DS",
"ITAR_BAU_L.3DS",
"ITAR_BAU_M.3DS",
"ITAR_BDT_H.3DS",
"ITAR_BDT_M.3DS",
"ITAR_CORANGAR.3DS",
"ITAR_DIEGO.3DS",
"ITAR_DJG_CRAWLER.3DS",
"ITAR_DJG_H.3DS",
"ITAR_DJG_L.3DS",
"ITAR_DJG_M.3DS",
"ITAR_GOVERNOR.3DS",
"ITAR_KDF_H.3DS",
"ITAR_KDF_L.3DS",
"ITAR_KDW_H.3DS",
"ITAR_LEATHER_L.3DS",
"ITAR_LESTER.3DS",
"ITAR_MIL_L.3DS",
"ITAR_MIL_M.3DS",
"ITAR_NOV_L.3DS",
"ITAR_PAL_H.3DS",
"ITAR_PAL_M.3DS",
"ITAR_PRISONER.3DS",
"ITAR_SLD_H.3DS",
"ITAR_SLD_L.3DS",
"ITAR_SLD_M.3DS",
"ITAR_SMITH.3DS",
"ITAR_TESTDUMMY.3DS",
"ITAR_VLKBABE.3DS",
"ITAR_VLK_H.3DS",
"ITAR_VLK_L.3DS",
"ITAR_VLK_M.3DS",
"ITAR_WIRT.3DS",
"ITAR_XARDAS.3DS",
"ITAT_BUGMANDIBLES.3DS",
"ITAT_CLAW.3DS",
"ITAT_CRAWLERMANDIBLES.3DS",
"ITAT_CRAWLERPLATE.3DS",
"ITAT_DEMONHEART.3DS",
"ITAT_DRAGONBLOOD.3DS",
"ITAT_DRAGONEGG.3DS",
"ITAT_DRAGONSCALE.3DS",
"ITAT_DRGSNAPPERHORN.3DS",
"ITAT_FIREDRAGONHEART.3DS",
"ITAT_FIREGOLEMHEART.3DS",
"ITAT_GOBLINBONE.3DS",
"ITAT_ICEDRAGONHEART.3DS",
"ITAT_ICEGOLEMHEART.3DS",
"ITAT_LURKERCLAW.3DS",
"ITAT_LURKERSKIN.3DS",
"ITAT_MEATBUGFLESH.3DS",
"ITAT_ROCKDRAGONHEART.3DS",
"ITAT_SHADOWFUR.3DS",
"ITAT_SHADOWHORN.3DS",
"ITAT_SHARKSKIN.3DS",
"ITAT_SHARKTEETH.3DS",
"ITAT_SHEEPFUR.3DS",
"ITAT_SKELETONBONE.3DS",
"ITAT_STING.3DS",
"ITAT_STONEGOLEMHEART.3DS",
"ITAT_SWAMPDRAGONHEART.3DS",
"ITAT_TEETH.3DS",
"ITAT_TROLLFUR.3DS",
"ITAT_TROLLTOOTH.3DS",
"ITAT_UNDEADDRAGONSOULSTONE.3DS",
"ITAT_WARANFIRETONGUE.3DS",
"ITAT_WARGFUR.3DS",
"ITAT_WING.3DS",
"ITAT_WOLFFUR.3DS",
"ITFOMUTTON.3DS",
"ITFOMUTTONRAW.3DS",
"ITFO_APPLE.3DS",
"ITFO_BACON.3DS",
"ITFO_BEER.3DS",
"ITFO_BOOZE.3DS",
"ITFO_BREAD.3DS",
"ITFO_CHEESE.3DS",
"ITFO_FISH.3DS",
"ITFO_FISHSOUP.3DS",
"ITFO_HONEY.3DS",
"ITFO_MILK.3DS",
"ITFO_SAUSAGE.3DS",
"ITFO_STEW.3DS",
"ITFO_WATER.3DS",
"ITFO_WINE.3DS",
"ITFO_WINEBERRYS_01.3DS",
"ITKE_KEY_01.3DS",
"ITKE_KEY_02.3DS",
"ITKE_KEY_03.3DS",
"ITKE_LOCKPICK.3DS",
"ITLS_TORCHBURNED_01.3DS",
"ITLS_TORCH_01.3DS",
"ITMISWORDBLADE.3DS",
"ITMISWORDBLADEHOT.3DS",
"ITMISWORDRAW.3DS",
"ITMISWORDRAWHOT.3DS",
"ITMI_AQUAMARINE.3DS",
"ITMI_BROOM.3DS",
"ITMI_BRUSH.3DS",
"ITMI_COAL.3DS",
"ITMI_DARKPEARL.3DS",
"ITMI_FLASK.3DS",
"ITMI_GOLD.3DS",
"ITMI_GOLDCANDLEHOLDER.3DS",
"ITMI_GOLDCHALICE.3DS",
"ITMI_GOLDCHEST.3DS",
"ITMI_GOLDCUP.3DS",
"ITMI_GOLDNECKLACE.3DS",
"ITMI_GOLDPLATE.3DS",
"ITMI_GOLDRING.3DS",
"ITMI_HAMMER.3DS",
"ITMI_HOLYWATER.3DS",
"ITMI_INNOSEYE_BROKEN_MIS.3DS",
"ITMI_INNOSEYE_DISCHARGED_MIS.3DS",
"ITMI_INNOSEYE_MIS.3DS",
"ITMI_INNOSSTATUE.3DS",
"ITMI_JEWELERYCHEST.3DS",
"ITMI_JOINT.3DS",
"ITMI_JOINT_GER.3DS",
"ITMI_JOINT_US.3DS",
"ITMI_LUTE.3DS",
"ITMI_MOLERATLUBRIC.3DS",
"ITMI_NUGGET.3DS",
"ITMI_OLDCOIN.3DS",
"ITMI_PACKET.3DS",
"ITMI_PAN.3DS",
"ITMI_PANFULL.3DS",
"ITMI_PITCH.3DS",
"ITMI_PLIERS.3DS",
"ITMI_POCKET.3DS",
"ITMI_QUARTZ.3DS",
"ITMI_RAKE.3DS",
"ITMI_RING_01.3DS",
"ITMI_RING_01.3DS",
"ITMI_ROCKCRYSTAL.3DS",
"ITMI_RUNEBLANK.3DS",
"ITMI_SAW.3DS",
"ITMI_SCOOP.3DS",
"ITMI_SEXTANT.3DS",
"ITMI_SILVERCANDLEHOLDER.3DS",
"ITMI_SILVERCHALICE.3DS",
"ITMI_SILVERCUP.3DS",
"ITMI_SILVERNECKLACE.3DS",
"ITMI_SILVERPLATE.3DS",
"ITMI_SILVERRING.3DS",
"ITMI_STOMPER.3DS",
"ITMI_STONEOFKNOWLEGDE_MIS.3DS",
"ITMI_SULFUR.3DS",
"ITMW_005_1H_DAGGER_01.3DS",
"ITMW_005_1H_POKER_01.3DS",
"ITMW_007_1H_SICKLE_01.3DS",
"ITMW_008_1H_MACE_LIGHT_01.3DS",
"ITMW_008_1H_POLE_01.3DS",
"ITMW_010_1H_CLUB_01.3DS",
"ITMW_010_1H_SLEDGEHAMMER_01.3DS",
"ITMW_010_1H_SWORD_SHORT_01.3DS",
"ITMW_010_1H_VLK_HATCHET_01.3DS",
"ITMW_012_1H_KNIFE_02.3DS",
"ITMW_012_1H_NAILMACE_01.3DS",
"ITMW_012_1H_SCYTHE_01.3DS",
"ITMW_012_1H_SWORD_SHORT_02.3DS",
"ITMW_016_1H_SWORD_SHORT_03.3DS",
"ITMW_018_1H_MACE_01.3DS",
"ITMW_018_1H_SWORDCANE_01.3DS",
"ITMW_020_1H_SWORD_OLD_01.3DS",
"ITMW_020_1H_SWORD_SHORT_04.3DS",
"ITMW_020_2H_AXE_LUMBERJACK_01.3DS",
"ITMW_020_2H_NOV_STAFF_01.3DS",
"ITMW_020_2H_PICKAXE_01.3DS",
"ITMW_022_1H_MACE_WAR_01.3DS",
"ITMW_025_1H_MIL_SWORD_BROAD_01.3DS",
"ITMW_025_1H_SLD_AXE_01.3DS",
"ITMW_025_1H_SLD_SWORD_01.3DS",
"ITMW_025_1H_SWORD_SHORT_05.3DS",
"ITMW_025_2H_MISC_AXE_OLD_01.3DS",
"ITMW_025_2H_STAFF_02.3DS",
"ITMW_025_2H_SWORD_OLD_01.3DS",
"ITMW_028_1H_MACE_02.3DS",
"ITMW_028_1H_WARHAMMER_01.3DS",
"ITMW_028_2H_HALBERD_01.3DS",
"ITMW_030_1H_AXE_01.3DS",
"ITMW_030_1H_COMMON_SWORD_01.3DS",
"ITMW_030_1H_PAL_SWORD_02.3DS",
"ITMW_030_1H_PAL_SWORD_BASTARD_RAW_01.3DS",
"ITMW_030_1H_SWORD_03.3DS",
"ITMW_030_1H_SWORD_LONG_01.3DS",
"ITMW_030_2H_KDF_HAMMER_01.3DS",
"ITMW_032_2H_STAFF_03.3DS",
"ITMW_032_2H_SWORD_LIGHT_01.3DS",
"ITMW_035_1H_MACE_03.3DS",
"ITMW_035_1H_MACE_WAR_02.3DS",
"ITMW_035_1H_SWORD_04.3DS",
"ITMW_035_2H_AXE_LIGHT_03.3DS",
"ITMW_035_2H_SLD_AXE_01.3DS",
"ITMW_035_2H_SLD_SWORD_01.3DS",
"ITMW_037_1H_SWORD_LONG_02.3DS",
"ITMW_040_1H_AXE_02.3DS",
"ITMW_040_1H_AXE_03.3DS",
"ITMW_040_2H_PAL_SWORD_03.3DS",
"ITMW_040_2H_PAL_SWORD_HEAVY_RAW_01.3DS",
"ITMW_045_1H_MACE_04.3DS",
"ITMW_045_1H_SWORD_BASTARD_01.3DS",
"ITMW_045_1H_SWORD_LONG_04.3DS",
"ITMW_045_1H_SWORD_SMITH_02.3DS",
"ITMW_050_1H_MACE_WAR_03.3DS",
"ITMW_050_1H_SWORD_05.3DS",
"ITMW_050_1H_SWORD_RAPIER_01.3DS",
"ITMW_050_2H_SWORD_SMITH_02.3DS",
"ITMW_055_1H_SWORD_LONG_05.3DS",
"ITMW_055_2H_SWORD_LIGHT_05.3DS",
"ITMW_058_1H_SWORD_BASTARD_02.3DS",
"ITMW_058_1H_WARHAMMER_02.3DS",
"ITMW_060_1H_MACE_WAR_04.3DS",
"ITMW_060_1H_SWORD_SMITH_03.3DS",
"ITMW_060_2H_AXE_HEAVY_01.3DS",
"ITMW_060_2H_SWORD_01.3DS",
"ITMW_065_1H_SWORDCANE_02.3DS",
"ITMW_065_1H_SWORD_BASTARD_03.3DS",
"ITMW_065_1H_SWORD_BASTARD_04.3DS",
"ITMW_065_1H_WARHAMMER_03.3DS",
"ITMW_065_2H_GREATAXE_01.3DS",
"ITMW_068_2H_SWORD_02.3DS",
"ITMW_070_2H_AXE_HEAVY_03.3DS",
"ITMW_070_2H_SWORD_09.3DS",
"ITMW_070_2H_SWORD_SMITH_03.3DS",
"ITMW_075_1H_SWORD_SMITH_04.3DS",
"ITMW_075_2H_AXE_HEAVY_04.3DS",
"ITMW_075_2H_SWORD_HEAVY_03.3DS",
"ITMW_080_2H_AXE_HEAVY_02.3DS",
"ITMW_080_2H_SWORD_HEAVY_04.3DS",
"ITMW_090_1H_SWORD_SMITH_05.3DS",
"ITMW_090_2H_SWORD_SMITH_04.3DS",
"ITMW_110_2H_SWORD_SMITH_05.3DS",
"ITMW_2H_ORCAXE_01.3DS",
"ITMW_2H_ORCAXE_02.3DS",
"ITMW_2H_ORCAXE_03.3DS",
"ITMW_2H_ORCAXE_04.3DS",
"ITMW_2H_ORCMACE_01.3DS",
"ITMW_2H_ORCSWORD_01.3DS",
"ITMW_2H_ORCSWORD_02.3DS",
"ITPL_BEET.3DS",
"ITPL_BLUEPLANT.3DS",
"ITPL_DEX_HERB_01.3DS",
"ITPL_FORESTBERRY.3DS",
"ITPL_HEALTH_HERB_01.3DS",
"ITPL_HEALTH_HERB_02.3DS",
"ITPL_HEALTH_HERB_03.3DS",
"ITPL_MANA_HERB_01.3DS",
"ITPL_MANA_HERB_02.3DS",
"ITPL_MANA_HERB_03.3DS",
"ITPL_MUSHROOM_01.3DS",
"ITPL_MUSHROOM_02.3DS",
"ITPL_PERM_HERB.3DS",
"ITPL_PLANEBERRY.3DS",
"ITPL_SPEED_HERB_01.3DS",
"ITPL_STRENGTH_HERB_01.3DS",
"ITPL_SWAMPHERB.3DS",
"ITPL_TEMP_HERB.3DS",
"ITPL_WEED.3DS",
"ITPO_HEALTH_01.3DS",
"ITPO_HEALTH_02.3DS",
"ITPO_HEALTH_03.3DS",
"ITPO_MANA_01.3DS",
"ITPO_MANA_02.3DS",
"ITPO_MANA_03.3DS",
"ITPO_PERM_DEX.3DS",
"ITPO_PERM_HEALTH.3DS",
"ITPO_PERM_MANA.3DS",
"ITPO_PERM_STR.3DS",
"ITPO_SPEED.3DS",
"ITRI_DEX_01.3DS",
"ITRI_DEX_02.3DS",
"ITRI_DEX_STRG_01.3DS",
"ITRI_HP_01.3DS",
"ITRI_HP_02.3DS",
"ITRI_HP_MANA_01.3DS",
"ITRI_MANA_01.3DS",
"ITRI_MANA_02.3DS",
"ITRI_PROT_EDGE_01.3DS",
"ITRI_PROT_EDGE_02.3DS",
"ITRI_PROT_FIRE_01.3DS",
"ITRI_PROT_FIRE_02.3DS",
"ITRI_PROT_MAGE_01.3DS",
"ITRI_PROT_MAGE_02.3DS",
"ITRI_PROT_POINT_01.3DS",
"ITRI_PROT_POINT_02.3DS",
"ITRI_PROT_TOTAL_01.3DS",
"ITRI_PROT_TOTAL_02.3DS",
"ITRI_STR_01.3DS",
"ITRI_STR_02.3DS",
"ITRU_ARMYOFDARKNESS.3DS",
"ITRU_BREATHOFDEATH.3DS",
"ITRU_CHARGEFIREBALL.3DS",
"ITRU_FEAR.3DS",
"ITRU_FIREBOLT.3DS",
"ITRU_FIRERAIN.3DS",
"ITRU_FIRESTORM.3DS",
"ITRU_FULLHEAL.3DS",
"ITRU_HARMUNDEAD.3DS",
"ITRU_ICEBOLT.3DS",
"ITRU_ICECUBE.3DS",
"ITRU_ICEWAVE.3DS",
"ITRU_INSTANTFIREBALL.3DS",
"ITRU_LIGHT.3DS",
"ITRU_LIGHTHEAL.3DS",
"ITRU_LIGHTNINGFLASH.3DS",
"ITRU_MASSDEATH.3DS",
"ITRU_MASTEROFDESASTER.3DS",
"ITRU_MEDIUMHEAL.3DS",
"ITRU_PALDESTROYEVIL.3DS",
"ITRU_PALFULLHEAL.3DS",
"ITRU_PALHOLYBOLT.3DS",
"ITRU_PALLIGHT.3DS",
"ITRU_PALLIGHTHEAL.3DS",
"ITRU_PALMEDIUMHEAL.3DS",
"ITRU_PALREPELEVIL.3DS",
"ITRU_PALTELEPORTSECRET.3DS",
"ITRU_PYROKINESIS.3DS",
"ITRU_SHRINK.3DS",
"ITRU_SLEEP.3DS",
"ITRU_SUMDEMON.3DS",
"ITRU_SUMGOBSKEL.3DS",
"ITRU_SUMGOL.3DS",
"ITRU_SUMSKEL.3DS",
"ITRU_SUMWOLF.3DS",
"ITRU_TELEPORTFARM.3DS",
"ITRU_TELEPORTMONASTERY.3DS",
"ITRU_TELEPORTOC.3DS",
"ITRU_TELEPORTOWDEMONTOWER.3DS",
"ITRU_TELEPORTPASSNW.3DS",
"ITRU_TELEPORTPASSOW.3DS",
"ITRU_TELEPORTSEAPORT.3DS",
"ITRU_TELEPORTXARDAS.3DS",
"ITRU_TELEPORT_2.3DS",
"ITRU_TELEPORT_3.3DS",
"ITRU_THUNDERBALL.3DS",
"ITRU_WINDFIST.3DS",
"ITRU_ZAP.3DS",
"ITRW_ARROW.3DS",
"ITRW_BOLT.3DS",
"ITSC_ARMYOFDARKNESS.3DS",
"ITSC_BREATHOFDEATH.3DS",
"ITSC_CHARGEFIREBALL.3DS",
"ITSC_FEAR.3DS",
"ITSC_FIREBOLT.3DS",
"ITSC_FIRERAIN.3DS",
"ITSC_FIRESTORM.3DS",
"ITSC_FULLHEAL.3DS",
"ITSC_HARMUNDEAD.3DS",
"ITSC_ICEBOLT.3DS",
"ITSC_ICECUBE.3DS",
"ITSC_ICEWAVE.3DS",
"ITSC_INSTANTFIREBALL.3DS",
"ITSC_LIGHT.3DS",
"ITSC_LIGHTHEAL.3DS",
"ITSC_LIGHTNINGFLASH.3DS",
"ITSC_MASSDEATH.3DS",
"ITSC_MEDIUMHEAL.3DS",
"ITSC_PALDESTROYEVIL.3DS",
"ITSC_PALFULLHEAL.3DS",
"ITSC_PALHOLYBOLT.3DS",
"ITSC_PALLIGHT.3DS",
"ITSC_PALLIGHTHEAL.3DS",
"ITSC_PALMEDIUMHEAL.3DS",
"ITSC_PALREPELEVIL.3DS",
"ITSC_PYROKINESIS.3DS",
"ITSC_SHRINK.3DS",
"ITSC_SLEEP.3DS",
"ITSC_SUMDEMON.3DS",
"ITSC_SUMGOBSKEL.3DS",
"ITSC_SUMGOL.3DS",
"ITSC_SUMSKEL.3DS",
"ITSC_SUMWOLF.3DS",
"ITSC_THUNDERBALL.3DS",
"ITSC_TRFDRAGONSNAPPER.3DS",
"ITSC_TRFFIREWARAN.3DS",
"ITSC_TRFGIANTBUG.3DS",
"ITSC_TRFGIANTRAT.3DS",
"ITSC_TRFLURKER.3DS",
"ITSC_TRFSCAVENGER.3DS",
"ITSC_TRFSHADOWBEAST.3DS",
"ITSC_TRFSHEEP.3DS",
"ITSC_TRFSNAPPER.3DS",
"ITSC_TRFWARAN.3DS",
"ITSC_TRFWARG.3DS",
"ITSC_TRFWOLF.3DS",
"ITSC_WINDFIST.3DS",
"ITSC_ZAP.3DS",
"ITWR_BOOK_01.3DS",
"ITWR_BOOK_02_01.3DS",
"ITWR_BOOK_02_02.3DS",
"ITWR_BOOK_02_03.3DS",
"ITWR_BOOK_02_04.3DS",
"ITWR_BOOK_02_05.3DS",
"ITWR_MAP_01.3DS",
"ITWR_SCROLL_01.3DS",
"ITWR_SCROLL_02.3DS",
"LIGHT.3DS",
};

--SS_LoadSavedVobs();
Player = {};
local EditorTex = CreateTexture(5600, 4450, 8000, 7200, "Menu_Ingame.TGA")
local EditorTex2 = CreateTexture(5600, 6050, 8000, 7200, "Menu_Ingame.TGA")
-----------------------
local EditorCat1 = CreateTexture(5620, 5680, 6220, 6080, "Menu_Ingame.TGA") --5880
local EditorCat2 = CreateTexture(6200, 5680, 6800, 6080, "Menu_Ingame.TGA")
local EditorCat3 = CreateTexture(6780, 5680, 7380, 6080, "Menu_Ingame.TGA")
local EditorCat4 = CreateTexture(7360, 5680, 7970, 6080, "Menu_Ingame.TGA")
--matrix = require 'Modules/matrix'
--Quaternion = require 'Modules/1'

function OnFilterscriptInit ()
	SS_LoadSavedVobs();
	--SS_InitializeDraws();
end

function SS_InitializePlayerDraws ()
	
end

function SS_LoadSavedVobs()
	--print('1');
	local ctr = 0
	for _ in io.lines 'Vobs/Saved.txt' do
		ctr = ctr + 1;
	end
	--print('1');
	local vobload = io.open("Vobs/Saved.txt","r+");
	local temporary = nil;
	--print('1');
	for i = 0, ctr do
		temporary = vobload:read("*l");
		nowid = nil;
		--print('1');
		if temporary ~= nil then
			local sult, x, y, z, r_x, r_y, r_z, model, wrld = sscanf(temporary, "ffffffss");
			if sult == 1 then
				--print('1');
				local _n = #SavedVobs;
				SavedVobs[(_n+1)] = Vob.Create(model, wrld, x, y, z);
				SavedVobs[(_n+1)]:SetRotation(r_x, r_y, r_z);
			end
		end
	end
	vobload:close();
end

for i = 0, GetMaxPlayers() do
	Player[i] = {};
end

function SS_Default_Params(playerid)
	Player[playerid].SS = true;
	Player[playerid].nmodel = 1;
	Player[playerid].Catalog = 1;
	Player[playerid].coord_x = nil;
	Player[playerid].coord_y = nil;
	Player[playerid].coord_z = nil;
	Player[playerid].coord_r_x = nil;
	Player[playerid].coord_r_y = nil;
	Player[playerid].coord_r_z = nil;
	Player[playerid].SS_already = true;
	if Player[playerid].SS_ms == nil then
		Player[playerid].SS_ms = 10;
		Player[playerid].SS_rs = 10;
	end
	EditorDraw1 = CreatePlayerDraw(playerid, 5650, 4500, "Name: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
    EditorDraw2 = CreatePlayerDraw(playerid, 5650, 4700, "X: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
     EditorDraw3 = CreatePlayerDraw(playerid, 5650, 4900, "Y: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
     EditorDraw4 = CreatePlayerDraw(playerid, 5650, 5100, "Z: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
     EditorDraw5 = CreatePlayerDraw(playerid, 5650, 5300, "Скорость движения: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
     EditorDraw6 = CreatePlayerDraw(playerid, 5650, 5500, "Скорость поворота: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw6n1 = CreatePlayerDraw(playerid, 5800, 5800, "ALL", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw6n2 = CreatePlayerDraw(playerid, 6330, 5800, "MISC", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw7 = CreatePlayerDraw(playerid, 5650, 6100, "Для помощи пишите //help ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw8 = CreatePlayerDraw(playerid, 5650, 6300, "Выбор VOB - '[ | ]'", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw9 = CreatePlayerDraw(playerid, 5650, 6500, "Выбор скорости движения - '- | +' ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw10 = CreatePlayerDraw(playerid, 5650, 6700, "Выбор скорости прокрутки - '< | >' ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	 EditorDraw11 = CreatePlayerDraw(playerid, 5650, 6900, "Настроить высоту - 'j | k' ", "Font_Old_10_White_Hi.TGA", 255, 255, 255) --5880
end

function SS_Help(playerid)
			SendPlayerMessage(playerid,0, 188, 212,"=========================================");
			SendPlayerMessage(playerid,0, 188, 212,"//new (//n) - создать новый VOB объект.");
			SendPlayerMessage(playerid,0, 188, 212,"//del - удалить выбранный VOB объект.");
			SendPlayerMessage(playerid,0, 188, 212,"//b - переключать камеру обратно на игрока");
			SendPlayerMessage(playerid,0, 188, 212,"(выйти из режима редактирования(просмотра))");
			SendPlayerMessage(playerid,0, 188, 212,"//v - режим просмотра(редактирования).");
			SendPlayerMessage(playerid,0, 188, 212,"//с - скопировать выбранный VOB объект.");
			SendPlayerMessage(playerid,0, 188, 212,"//d - какаята хуйня.");
			SendPlayerMessage(playerid,0, 188, 212,"//s - сохранить выбранный VOB в saved.txt");
			SendPlayerMessage(playerid,0, 188, 212,"//dis - дисплей.");
			SendPlayerMessage(playerid,0, 188, 212,"Переключение существующих VOB на Q и E");
			SendPlayerMessage(playerid,0, 188, 212,"=========================================");
end

function SS_Startup_MSG(playerid)
	--Cyan(rgb(0, 188, 212))
	local __n = Vob.GetNumberOfVobs();
	--local EditorTex = CreateTexture(5600, 2000, 6800, 4000, "Menu_Ingame.TGA")
	SendPlayerMessage(playerid,0, 188, 212,"=============================");
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Вы вошли в SlashSlash! (v1.0b)");
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Выход: //ss. При повторном заходе пароль не требуется.");
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Создатель: elia_morrison");
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Помощь: //help");
	if Player[playerid].SS_ms == nil then
		SendPlayerMessage(playerid,0, 188, 212,"(SS) Скорость движения: 10.");
		SendPlayerMessage(playerid,0, 188, 212,"(SS) Скорость поворота: 10.");
	else
		SendPlayerMessage(playerid,0, 188, 212,"(SS) Скорость движения: "..tostring(Player[playerid].SS_ms));
		SendPlayerMessage(playerid,0, 188, 212,"(SS) Скорость поворота: "..tostring(Player[playerid].SS_rs));
	end
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Всего вобов: "..__n);
	SendPlayerMessage(playerid,0, 188, 212,"=============================");
end

function SS_Reset_Params(playerid)
	Player[playerid].SS = nil;
	Player[playerid].nmodel = 1;
	Player[playerid].already = nil;
	Player[playerid].SS_ms = nil;
	Player[playerid].SS_rs = nil;
	Player[playerid].SS_cvob = nil;
	HideTexture(playerid,EditorTex) --EditorCat1
	HideTexture(playerid,EditorTex2)
	HideTexture(playerid,EditorCat1)
	HideTexture(playerid,EditorCat2)
	HideTexture(playerid,EditorCat3)
	HideTexture(playerid,EditorCat4)
	--KillTimer(Player[playerid].SS_fw_timer);
	Player[playerid].SS_fw_timer = nil;
end

function SS_Quit(playerid)
	Player[playerid].SS = nil;
	Player[playerid].nmodel = 1;
	Player[playerid].SS_cvob = nil;
	SetDefaultCamera(playerid);
	HideTexture(playerid,EditorTex)
	HideTexture(playerid,EditorTex2)
	HideTexture(playerid,EditorCat1)
	HideTexture(playerid,EditorCat2)
	HideTexture(playerid,EditorCat3)
	HideTexture(playerid,EditorCat4)
	HidePlayerDraw(playerid,EditorDraw1)
	HidePlayerDraw(playerid,EditorDraw2)
	HidePlayerDraw(playerid,EditorDraw3)
	HidePlayerDraw(playerid,EditorDraw4)
	HidePlayerDraw(playerid,EditorDraw5)
	HidePlayerDraw(playerid,EditorDraw6)
	HidePlayerDraw(playerid,EditorDraw6n1)
	HidePlayerDraw(playerid,EditorDraw6n2)
	HidePlayerDraw(playerid,EditorDraw7)
	HidePlayerDraw(playerid,EditorDraw8)
	HidePlayerDraw(playerid,EditorDraw9)
	HidePlayerDraw(playerid,EditorDraw10)
	HidePlayerDraw(playerid,EditorDraw11)
	FreezePlayer(playerid, 0);
	--[[KillTimer(Player[playerid].SS_fw_timer);
	Player[playerid].SS_fw_timer = nil;
	KillTimer(Player[playerid].SS_bw_timer);
	Player[playerid].SS_bw_timer = nil;
	KillTimer(Player[playerid].SS_lt_timer);
	Player[playerid].SS_lt_timer = nil;
	KillTimer(Player[playerid].SS_rt_timer);
	Player[playerid].SS_rt_timer = nil;
	KillTimer(Player[playerid].SS_md_timer);
	Player[playerid].SS_md_timer = nil;
	KillTimer(Player[playerid].SS_mu_timer);
	Player[playerid].SS_mu_timer = nil;]]
	SendPlayerMessage(playerid,0, 188, 212,"=============================");
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Вы вышли из SlashSlash!");
	SendPlayerMessage(playerid,0, 188, 212,"=============================");
end

function SS_Speed (playerid)
	UpdatePlayerDraw(playerid, EditorDraw5, 5650, 5300, "Скорость движения: "..Player[playerid].SS_ms, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw6, 5650, 5500, "Скорость поворота: "..Player[playerid].SS_rs, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
end

function SS_Movement_Forward (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	local x, y, z = VobIDs[_f]:GetPosition();
	local _sin = math.sin(math.rad(r_y));
	local _cos = math.cos(math.rad(r_y));
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255) --Player[playerid].SS_ms
	x = x + Player[playerid].SS_ms * _sin;
	z = z + Player[playerid].SS_ms * _cos;
	VobIDs[_f]:SetPosition(x,y,z);
end

function SS_Movement_Backward (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	local x, y, z = VobIDs[_f]:GetPosition();
	local _sin = math.sin(math.rad(r_y));
	local _cos = math.cos(math.rad(r_y));
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	x = x - Player[playerid].SS_ms * _sin;
	z = z - Player[playerid].SS_ms * _cos;
	VobIDs[_f]:SetPosition(x,y,z);
end

function SS_Movement_Up (playerid)
	local _f = Player[playerid].SS_cID;
	local x, y, z = VobIDs[_f]:GetPosition();
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	y = y + Player[playerid].SS_ms;
	VobIDs[_f]:SetPosition(x,y,z);
end

function SS_Movement_Down (playerid)
	local _f = Player[playerid].SS_cID;
	local x, y, z = VobIDs[_f]:GetPosition();
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	y = y - Player[playerid].SS_ms;
	VobIDs[_f]:SetPosition(x,y,z);
end

function SS_Rotation_Left (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation()
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	VobIDs[_f]:SetRotation(r_x, r_y-Player[playerid].SS_rs, r_z);
	--r_z*math.sin(math.rad(r_z))+r_z*math.cos(math.rad(r_z)));]]
	-- Пустая 3х3 матрица: matrix{{0,0,0},{0,0,0}{0,0,0}};
	--[[local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	SendPlayerMessage(playerid,0, 188, 212,"(SS) "..r_x..r_y..r_z);
	local MatrixLocal = matrix{{1,0,0},{0,1,0},{0,0,1}};
	local MatrixOX = matrix{{1,0,0},{0,math.cos(math.rad(r_x)),math.sin(math.rad(r_x))},{0,-math.sin(math.rad(r_x)),math.cos(math.rad(r_x))}};
	local MatrixOY = matrix{{math.cos(math.rad(r_y)),0,-math.sin(math.rad(r_y))},{0,1,0},{math.sin(math.rad(r_y)),0,math.cos(math.rad(r_y))}};
	local MatrixOZ = matrix{{math.cos(math.rad(r_z)),math.sin(math.rad(r_z)),0},{-math.sin(math.rad(r_z)),math.cos(math.rad(r_z)),0},{0,0,1}};
	local FinalMatrix = matrix.mul(matrix.invert(MatrixOZ), matrix.mul(matrix.invert(MatrixOY), matrix.mul(matrix.invert(MatrixOX), MatrixLocal)));
	--SendPlayerMessage(playerid,0, 188, 212,"(SS) Final: "..matrix.getelement(FinalMatrix, 1, 1)..matrix.getelement(FinalMatrix, 1, 2)..matrix.getelement(FinalMatrix, 1, 3));
	local CoordMatrix = matrix{{r_x},{r_y},{r_z}};
	--CoordMatrix = matrix.mul(FinalMatrix, CoordMatrix);
	--SendPlayerMessage(playerid,0, 188, 212,"(SS) "..matrix.getelement(CoordMatrix, 1, 1)..matrix.getelement(CoordMatrix, 1, 2)..matrix.getelement(CoordMatrix, 1, 3));
	VobIDs[_f]:SetRotation(r_x*math.cos(math.rad(r_x))-r_x*(math.sin(math.rad(r_x))), 
	(r_y+Player[playerid].SS_rs/5), 
	r_z*math.sin(math.rad(r_z))+r_z*math.cos(math.rad(r_z)));]]
	--[[local r_x_n = matrix.getelement(FinalMatrix, 1, 1)*r_x + matrix.getelement(FinalMatrix, 1, 2)*r_y + matrix.getelement(FinalMatrix, 1, 3)*r_z;
	local r_y_n = matrix.getelement(FinalMatrix, 2, 1)*r_x + matrix.getelement(FinalMatrix, 2, 2)*r_y + matrix.getelement(FinalMatrix, 2, 3)*r_z;
	local r_z_n = matrix.getelement(FinalMatrix, 3, 1)*r_x + matrix.getelement(FinalMatrix, 3, 2)*r_y + matrix.getelement(FinalMatrix, 3, 3)*r_z;
	local r_y_n = r_y_n + Player[playerid].SS_rs/5;
	VobIDs[_f]:SetRotation(r_x, r_y_n, r_z);]]
end

function SS_Rotation_Right (playerid)
	-- Пустая 3х3 матрица: matrix{{0,0,0},{0,0,0}{0,0,0}};
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	VobIDs[_f]:SetRotation(r_x, r_y+Player[playerid].SS_rs, r_z);
	--local __x, __y, __z = VobIDs[_f]:GetPosition();
	--SendPlayerMessage(playerid,0, 188, 212,"(SS) "..r_x..r_y..r_z);
	--[[local MatrixLocal = matrix{{1,0,0},{0,1,0},{0,0,1}};
	local MatrixOX = matrix{{1,0,0,0},{0,math.cos(math.rad(r_x)),math.sin(math.rad(r_x)),0},{0,-math.sin(math.rad(r_x)),math.cos(math.rad(r_x)),0},{0,0,0,1}};
	local MatrixOY = matrix{{math.cos(math.rad(r_y)),0,-math.sin(math.rad(r_y)),0},{0,1,0,0},{math.sin(math.rad(r_y)),0,math.cos(math.rad(r_y)),0},{0,0,0,1}};
	local MatrixOZ = matrix{{math.cos(math.rad(r_z)),math.sin(math.rad(r_z)),0,0},{-math.sin(math.rad(r_z)),math.cos(math.rad(r_z)),0},{0,0,1,0},{0,0,0,1}};
	local MatrixMov = matrix{{1,0,0,0},{0,1,0,0},{0,0,1,0},{__x,__y,__z, 1}};
	local FinalMatrix = matrix.mul(matrix.invert(MatrixOZ), matrix.mul(matrix.invert(MatrixOY), matrix.mul(matrix.invert(MatrixOX), MatrixLocal)));
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Final: "..matrix.getelement(FinalMatrix, 1, 1)..matrix.getelement(FinalMatrix, 1, 2)..matrix.getelement(FinalMatrix, 1, 3));
	local CoordMatrix = matrix{{r_x},{r_y},{r_z}};
	CoordMatrix = matrix.mul(FinalMatrix, CoordMatrix);
	SendPlayerMessage(playerid,0, 188, 212,"(SS) "..matrix.getelement(CoordMatrix, 1, 1)..matrix.getelement(CoordMatrix, 1, 2)..matrix.getelement(CoordMatrix, 1, 3));
	VobIDs[_f]:SetRotation(r_x*math.cos(math.rad(r_x))-r_x*(math.sin(math.rad(r_x))), 
	(r_y+Player[playerid].SS_rs/5), 
	r_z*math.sin(math.rad(r_z))+r_z*math.cos(math.rad(r_z)));
	local r_x_n = matrix.getelement(FinalMatrix, 1, 1)*r_x + matrix.getelement(FinalMatrix, 1, 2)*r_y + matrix.getelement(FinalMatrix, 1, 3)*r_z;
	local r_y_n = matrix.getelement(FinalMatrix, 2, 1)*r_x + matrix.getelement(FinalMatrix, 2, 2)*r_y + matrix.getelement(FinalMatrix, 2, 3)*r_z;
	local r_z_n = matrix.getelement(FinalMatrix, 3, 1)*r_x + matrix.getelement(FinalMatrix, 3, 2)*r_y + matrix.getelement(FinalMatrix, 3, 3)*r_z;
	local r_y_n = r_y_n + Player[playerid].SS_rs/5;
	VobIDs[_f]:SetRotation(r_x, r_y_n, r_z);
	ТОЛЬКО МАТРИЦА OY. Раскачивание.
	local r_x_n = r_x*math.cos(math.rad(Player[playerid].SS_rs/5)) + r_z*math.sin(math.rad(Player[playerid].SS_rs/5));
	local r_y_n = r_y; + Player[playerid].SS_rs/5;
	local r_z_n = r_x*(-math.sin(math.rad(Player[playerid].SS_rs/5)))+r_z*math.cos(math.rad(Player[playerid].SS_rs/5));]]
	--[[local Quat = Quaternion.Euler(r_x, r_y, r_z);
	SendPlayerMessage(playerid,0, 188, 212,"(SS) "..Quat.x.." "..Quat.y.." "..Quat.z);
	Quat.y = Quat.y + Player[playerid].SS_rs/5;
	local Final_Euler = Quat:ToEulerAngles()
	VobIDs[_f]:SetRotation(Final_Euler.x, Final_Euler.y, Final_Euler.z);]]
end

function SS_Swing_Left (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	VobIDs[_f]:SetRotation(r_x, r_y, r_z+Player[playerid].SS_rs/5);
end

function SS_Swing_Right (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	VobIDs[_f]:SetRotation(r_x, r_y, r_z-Player[playerid].SS_rs/5);
end

function SS_Rotation_Forward (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	VobIDs[_f]:SetRotation(r_x+Player[playerid].SS_rs/5, r_y, r_z);
end

function SS_Rotation_Back (playerid)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	VobIDs[_f]:SetRotation(r_x-Player[playerid].SS_rs/5, r_y, r_z);
end

function OnPlayerCommandText(playerid, cmdtext)
	local cmd, params = GetCommand(cmdtext);
	if cmd == "//ss" then
	--SS_testing(playerid)
		if Player[playerid].SS ~= true then
			if Player[playerid].SS_already ~= true then
			SS_Startup(playerid)
				local result, _password = sscanf(params, "s");
				if result == 1 and SHA256(string.upper(_password)) == "0530" then
					SS_Startup(playerid);
				end
			else
				SS_Startup(playerid);
			end
		else
			SS_Quit(playerid);
		end
	end
	if Player[playerid].SS == true then
		if cmd == "//new" or cmd == "//n" then
			local x, y, z = GetPlayerPos(playerid);
			print(x, y, z)
			SS_NewVob(playerid, params);
		elseif cmd == "//help" then
			SS_Help(playerid);
		elseif cmd == "//del" then
			SS_Delete(playerid);
		elseif cmd == "//b" then
			SS_BackToCharacter(playerid);
		elseif cmd == "//v" then
			SS_View(playerid);
		elseif cmd == "//c" then
			SS_Copy(playerid);
		elseif cmd == "//d" then
			SS_Dump(playerid, params);
		elseif cmd == "//s" then
			SS_Save(playerid, params);
		elseif cmd == "//dis" then
			SS_Display(playerid);
		end
	end
end

function SS_Startup(playerid)
	SS_Startup_MSG(playerid);
	SS_Default_Params(playerid);
	SS_InitializePlayerDraws(playerid);
end

function SS_Dump (playerid, params)
	local result,filename = sscanf(params,"s");
	if result == 1 then
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	local x, y, z = VobIDs[_f]:GetPosition();
	local model = VobModels[_f];
	local file = io.open("Vobs/Voblist.txt","a");
	file:write(filename..' = Vob.Create("'..model..'", "'..GetPlayerWorld(playerid)..'", '..x..', '..y..', '..z..');\n');
	file:write(filename..':SetRotation('..r_x..', '..r_y..', '..r_z..');\n');
	file:close();
	SendPlayerMessage(playerid, 0, 188, 212,"(SS) Vob data dumped to "..filename..".");
else
	SendPlayerMessage(playerid, 0, 188, 212,"(SS) Use /d (filename)");
end
end

function SS_Save (playerid, params)
	local _f = Player[playerid].SS_cID;
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	local x, y, z = VobIDs[_f]:GetPosition();
	local model = VobModels[_f];
	local wrld = GetPlayerWorld(playerid);
	local file = io.open("Vobs/Saved.txt","a");
	file:write(x.." "..y.." "..z.." "..r_x.." "..r_y.." "..r_z.." "..model.." "..wrld.."\n");
	file:close();
	
	VobIDs[Player[playerid].SS_cID]:Destroy();
	
	
	if Player[playerid].SS_cID ~= #VobIDs then
	print("okk")
		for i = Player[playerid].SS_cID+1, #VobIDs do 
		print("poshlo")
			VobIDs[i-1] = VobIDs[i];
			VobModels[i-1] = VobModels[i];
		end
		--VobIDs[Player[playerid].SS_cID] = nil;
		--VobModels[Player[playerid].SS_cID] = nil;
	else
		VobIDs[Player[playerid].SS_cID] = nil;
		print("okkAAAAAAA")
	end
	
	local _n = #SavedVobs;
	print("savevob")
	SavedVobs[_f] = Vob.Create(model, wrld, x, y, z);
	SavedVobs[_f]:SetRotation(r_x, r_y, r_z);
	print("complide")
	
	if #VobIDs ~= 0 then
	print("chech vob")
		SS_ChangeVobLeft(playerid);
		print("left")
	elseif #VobIDs ~= #VobIDs then
	    VobIDs = VobIDs - 1 
	else
	print("back")
		SS_BackToCharacter(playerid);
	end
	SendPlayerMessage(playerid, 0, 188, 212,"(SS) Vob ".._f.." saved successfully.");
end

function SS_Display (playerid)
	local _f = Player[playerid].SS_cID;
	for i in pairs(VobIDs[_f]) do
        SendPlayerMessage(playerid, 0, 188, 212,"(SS) Parameter #"..i..": "..VobIDs[_f][i]);
    end
end

function SS_Copy (playerid)
	local _f = Player[playerid].SS_cID;
	local _x, _y, _z = VobIDs[_f]:GetPosition();
	local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
	local _n = #VobIDs;
	local vob_id = VobModels[_f];
	VobIDs[(_n+1)] = Vob.Create(vob_id, GetPlayerWorld(playerid), _x, _y, _z);
	VobIDs[(_n+1)]:SetRotation(r_x, r_y, r_z);
	VobModels[(_n+1)] = string.upper(vob_id);
	SS_Give_Control(playerid, VobIDs[(_n+1)], _n+1);
	Player[playerid].SS_cID = _n + 1;
	SendPlayerMessage(playerid, 0, 188, 212, "(SS) Вы скопировали "..vob_id.."!");

	--[[if result == 1 then
		local _f = Player[playerid].SS_cID;
		local r_x, r_y, r_z = VobIDs[_f]:GetRotation();
		local x, y, z = VobIDs[_f]:GetPosition();
		local _x, _y, _z = GetPlayerPos(playerid);
		local _n = #VobIDs;
		VobIDs[(_n+1)] = Vob.Create(vob_id, GetPlayerWorld(playerid), _x, _y, _z);
		SS_Give_Control(playerid, VobIDs[(_n+1)], _n+1);
		Player[playerid].SS_cID = _n + 1;
	else
		SS_Selection_Menu(playerid);
	end]]
end

function SS_View(playerid)
local _n = #VobIDs;
	if #VobIDs ~= 0 then
	--[[ShowTexture(playerid,EditorTex)
	ShowTexture(playerid,EditorTex2)
	ShowTexture(playerid,EditorCat1)
	ShowTexture(playerid,EditorCat2)
	ShowTexture(playerid,EditorCat3)
	ShowTexture(playerid,EditorCat4)
	ShowPlayerDraw(playerid,EditorDraw1)
	ShowPlayerDraw(playerid,EditorDraw2)
	ShowPlayerDraw(playerid,EditorDraw3)
	ShowPlayerDraw(playerid,EditorDraw4)
	ShowPlayerDraw(playerid,EditorDraw5)
	ShowPlayerDraw(playerid,EditorDraw6)
	ShowPlayerDraw(playerid,EditorDraw6n1)
	ShowPlayerDraw(playerid,EditorDraw6n2)
	ShowPlayerDraw(playerid,EditorDraw7)
	ShowPlayerDraw(playerid,EditorDraw8)
	ShowPlayerDraw(playerid,EditorDraw9)
	ShowPlayerDraw(playerid,EditorDraw10)
	ShowPlayerDraw(playerid,EditorDraw11)]]
		SS_Give_Control(playerid, VobIDs[1], 1);
	--elseif
	   -- SS_Give_Control(playerid, VobIDs[_n+1], _n+1);
	else
		SendPlayerMessage(playerid,0, 188, 212,"(SS) Нет вобов, доступных для просмотра.");
	end
end

function SS_BackToCharacter(playerid)
	Player[playerid].SS_cvob = nil;
	Player[playerid].SS_cID = nil;
	--[[HideTexture(playerid,EditorTex)
	HideTexture(playerid,EditorTex2)
	HideTexture(playerid,EditorCat1)
	HideTexture(playerid,EditorCat2)
	HideTexture(playerid,EditorCat3)
	HideTexture(playerid,EditorCat4)
	HidePlayerDraw(playerid,EditorDraw1)
	HidePlayerDraw(playerid,EditorDraw2)
	HidePlayerDraw(playerid,EditorDraw3)
	HidePlayerDraw(playerid,EditorDraw4)
	HidePlayerDraw(playerid,EditorDraw5)
	HidePlayerDraw(playerid,EditorDraw6)
	HidePlayerDraw(playerid,EditorDraw6n1)
	HidePlayerDraw(playerid,EditorDraw6n2)
	HidePlayerDraw(playerid,EditorDraw7)
	HidePlayerDraw(playerid,EditorDraw8)
	HidePlayerDraw(playerid,EditorDraw9)
	HidePlayerDraw(playerid,EditorDraw10)
	HidePlayerDraw(playerid,EditorDraw11)
	--[[KillTimer(Player[playerid].SS_fw_timer);
	Player[playerid].SS_fw_timer = nil;
	KillTimer(Player[playerid].SS_bw_timer);
	Player[playerid].SS_bw_timer = nil;
	KillTimer(Player[playerid].SS_lt_timer);
	Player[playerid].SS_lt_timer = nil;
	KillTimer(Player[playerid].SS_rt_timer);
	Player[playerid].SS_rt_timer = nil;
	KillTimer(Player[playerid].SS_md_timer);
	Player[playerid].SS_md_timer = nil;
	KillTimer(Player[playerid].SS_mu_timer);
	Player[playerid].SS_mu_timer = nil;]]
	SetDefaultCamera(playerid);
	FreezePlayer(playerid, 0);
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Вы вышли из режима просмотра/редактирования.");
end

function SS_Delete(playerid)
	if Player[playerid].SS_cvob ~= nil then
		VobIDs[Player[playerid].SS_cID]:Destroy();
		if Player[playerid].SS_cID ~= #VobIDs then
			for i = Player[playerid].SS_cID+1, #VobIDs do 
				VobIDs[i-1] = VobIDs[i];
				VobModels[i-1] = VobModels[i];
			end
			--VobIDs[Player[playerid].SS_cID] = nil;
			--VobModels[Player[playerid].SS_cID] = nil;
		else
			VobIDs[Player[playerid].SS_cID] = nil;
		end
		SendPlayerMessage(playerid,0, 188, 212,"(SS) Вы удалили: "..Player[playerid].SS_cID..".");
		if #VobIDs ~= 0 then
			SS_ChangeVobLeft(playerid);
		else
			SS_BackToCharacter(playerid);
		end
		
	end
end

function SS_testing(playerid)
	local fileRead = io.open("Vobs/vobs.txt","r");
	tempvar = fileRead:read("*l");
	tempvar = fileRead:read("*b");
	print(tempvar)
end

function SS_NewVob(playerid, params)
--[[if Player[playerid].SS_cvob ~= nil then
		VobIDs[Player[playerid].SS_cID]:Destroy();
		if Player[playerid].SS_cID ~= #VobIDs then
			for i = Player[playerid].SS_cID+1, #VobIDs do 
				VobIDs[i-1] = VobIDs[i];
				VobModels[i-1] = VobModels[i];
			end
			--VobIDs[Player[playerid].SS_cID] = nil;
			--VobModels[Player[playerid].SS_cID] = nil;
		else
			VobIDs[Player[playerid].SS_cID] = nil;
		end
end]]
	--local result, vob_id = sscanf(params,"s");
	--local fileRead = io.open("Vobs/vobs.txt","r");
	--string.lower(S); 
	--if result == 1 then
		local _x, _y, _z = GetPlayerPos(playerid);
		print(_x, _y, _z)
		local _n = #VobIDs;
		--EditorDraw2 = CreatePlayerDraw(playerid, 5650, 4700, "Координата X: ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
		--[[ShowPlayerDraw(playerid,EditorDraw1)
		ShowPlayerDraw (playerid, EditorDraw2)
		ShowPlayerDraw (playerid, EditorDraw3)
		ShowPlayerDraw (playerid, EditorDraw4)
		ShowPlayerDraw (playerid, EditorDraw5)
		ShowPlayerDraw (playerid, EditorDraw6)
		ShowPlayerDraw(playerid,EditorDraw6n1)
		ShowPlayerDraw(playerid,EditorDraw6n2)
		ShowPlayerDraw (playerid, EditorDraw7)
		ShowPlayerDraw (playerid, EditorDraw8)
		ShowPlayerDraw (playerid, EditorDraw9)
		ShowPlayerDraw (playerid, EditorDraw10)
		ShowPlayerDraw (playerid,EditorDraw11)]]
		--Objectlist[Editor[playerid].nmodel
		--[[if Player[playerid].nmodel ~= 67 then
		Player[playerid].nmodel = Player[playerid].nmodel+1
		else
		Player[playerid].nmodel = 1
		end]]
		--tempvar = fileRead:read("*l");
		--[[ShowTexture(playerid,EditorTex)
		ShowTexture(playerid,EditorTex2)
		ShowTexture(playerid,EditorCat1)
		ShowTexture(playerid,EditorCat2)
		ShowTexture(playerid,EditorCat3)
		ShowTexture(playerid,EditorCat4)]]
		if Player[playerid].Catalog == 1 then
		VobIDs[(_n+1)] = Vob.Create(Objectlist[Player[playerid].nmodel], GetPlayerWorld(playerid), _x, _y, _z);
		print(_x, _y, _z)
		VobModels[(_n+1)] = string.upper(Objectlist[Player[playerid].nmodel]);
		elseif Player[playerid].Catalog == 2 then
		VobIDs[(_n+1)] = Vob.Create(ObjectlistLn[Player[playerid].nmodel], GetPlayerWorld(playerid), _x, _y, _z);
		VobModels[(_n+1)] = string.upper(ObjectlistLn[Player[playerid].nmodel]);
		end
		local v_x,v_y,v_z = VobIDs[(_n+1)]:GetPosition()
		print(_x, _y, _z)
		print(v_x,v_y,v_z)
		UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
		UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
		UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
		SS_Give_Control(playerid, VobIDs[(_n+1)], _n+1);
		Player[playerid].SS_cID = _n + 1;
	--else
		--SS_Selection_Menu(playerid);
	--end
end

function SS_StandartRotation(playerid)
	local _f = Player[playerid].SS_cID;
	VobIDs[_f]:SetRotation(0, 0, 0);
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Вы обнулили поворот: "..Player[playerid].SS_cID..".");
end

function SS_Selection_Menu(playerid)
	
end

function SS_ChangeVobLeft(playerid)
    local _f = Player[playerid].SS_cID;
	--[[if #VobIDs ~= #VobIDs then
	for i = Player[playerid].SS_cID, #VobIDs do 
	Player[playerid].SS_cID = Player[playerid].SS_cID + #VobIDs
	end
	end]]
	--[[local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	--SS_VobId(playerid)
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)]]
	if Player[playerid].SS_cID -1  < 1 then
		SS_Give_Control(playerid, VobIDs[#VobIDs], #VobIDs);
	else
		SS_Give_Control(playerid, VobIDs[Player[playerid].SS_cID-1], Player[playerid].SS_cID-1);
	end
end

function SS_VobId(playerid)
    local _f = Player[playerid].SS_cID;
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	--UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	--UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	--UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
end

function SS_ChangeVobRight(playerid)
	local _f = Player[playerid].SS_cID;
	--[[local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)]]
	if Player[playerid].SS_cID + 1  < #VobIDs then
		SS_Give_Control(playerid, VobIDs[1], 1);
	else
		SS_Give_Control(playerid, VobIDs[Player[playerid].SS_cID+1], Player[playerid].SS_cID+1);
	end
end


function SS_Give_Control(playerid, control_vob, vob_id)
	SetCameraBehindVob(playerid, control_vob);
	FreezePlayer(playerid, 1);
	SendPlayerMessage(playerid,0, 188, 212,"(SS) Вы сейчас управляете: "..vob_id.." ("..VobModels[vob_id]..").");
	Player[playerid].SS_cvob = control_vob;
	Player[playerid].SS_cID = vob_id;
	local _f = Player[playerid].SS_cID;
	local v_x,v_y,v_z = VobIDs[_f]:GetPosition()
	--[[UpdatePlayerDraw(playerid, EditorDraw1, 5650, 4500, "Name: "..VobModels[vob_id], "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw2, 5650, 4700, "X: "..v_x, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw3, 5650, 4900, "Y: "..v_y, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw4, 5650, 5100, "Z: "..v_z, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw5, 5650, 5300, "Скорость движения: "..Player[playerid].SS_ms, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw6, 5650, 5500, "Скорость поворота: "..Player[playerid].SS_rs, "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw7, 5650, 6100, "Для помощи пишите //help", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw8, 5650, 6300, "Выбор VOB объекта - '[ | ]'", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw9, 5650, 6500, "Выбор скорости движения - '- | +'", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw10, 5650, 6700, "Выбор скорости прокрутки - '< | >'", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
	UpdatePlayerDraw(playerid, EditorDraw11, 5650, 6900, "Настроить высоту - 'j | k' ", "Font_Old_10_White_Hi.TGA", 255, 255, 255)]]
end

function OnPlayerKey(playerid, keyDown, keyUp)
	local x, y, z = GetPlayerPos(playerid)
	if keyDown == KEY_W then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_fw_timer = SetTimerEx("SS_Movement_Forward", 40, 1, playerid);
		end
	elseif keyUp == KEY_W then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_fw_timer);
		end
	elseif keyDown == KEY_S then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_bw_timer = SetTimerEx("SS_Movement_Backward", 40, 1, playerid);
		end
	elseif keyUp == KEY_S then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_bw_timer);
		end
	elseif keyDown == KEY_A then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_lt_timer = SetTimerEx("SS_Rotation_Left", 40, 1, playerid);
		end
	elseif keyUp == KEY_A then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_lt_timer);
		end
	elseif keyDown == KEY_D then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_rt_timer = SetTimerEx("SS_Rotation_Right", 40, 1, playerid);
		end
	elseif keyUp == KEY_D then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_rt_timer);
		end
	elseif keyDown == KEY_LEFT then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_sl_timer = SetTimerEx("SS_Swing_Left", 40, 1, playerid);
		end
	elseif keyUp == KEY_LEFT then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_sl_timer);
		end
	elseif keyDown == KEY_RIGHT then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_sr_timer = SetTimerEx("SS_Swing_Right", 40, 1, playerid);
		end
	elseif keyUp == KEY_RIGHT then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_sr_timer);
		end
	elseif keyDown == KEY_UP then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_rf_timer = SetTimerEx("SS_Rotation_Forward", 40, 1, playerid);
		end
	elseif keyUp == KEY_UP then --
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_rf_timer);
		end
	elseif keyDown == KEY_DOWN then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_rf_timerln = SetTimerEx("SS_Rotation_Back", 40, 1, playerid);
		end
	elseif keyUp == KEY_DOWN then
		if Player[playerid].SS_cvob ~= nil then
		    KillTimer(Player[playerid].SS_rf_timerln);
		end
	elseif keyDown == KEY_J then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_mu_timer = SetTimerEx("SS_Movement_Up", 40, 1, playerid);
		end
	elseif keyUp == KEY_J then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_mu_timer);
		end
	elseif keyDown == KEY_K then
		if Player[playerid].SS_cvob ~= nil then
			Player[playerid].SS_md_timer = SetTimerEx("SS_Movement_Down", 40, 1, playerid);
		end
	elseif keyUp == KEY_K then
		if Player[playerid].SS_cvob ~= nil then
			KillTimer(Player[playerid].SS_md_timer);
		end
	elseif keyDown == KEY_E then
		if Player[playerid].SS_cvob ~= nil then
			SS_ChangeVobRight(playerid);
		end
	elseif keyDown == KEY_Q then
		if Player[playerid].SS_cvob ~= nil then
			SS_ChangeVobLeft(playerid);
		end
	elseif keyDown == KEY_R then
		if Player[playerid].SS_cvob ~= nil then
			SS_StandartRotation(playerid);
		end
	elseif keyDown == KEY_LBRACKET then -- назад
	if Player[playerid].SS_cvob ~= nil then
         SS_period(playerid)
		 SS_one(playerid)
		end
	elseif keyDown == KEY_RBRACKET then -- вперед
		if Player[playerid].SS_cvob ~= nil then
           SS_period(playerid)
		   SS_two(playerid)
		end
	elseif keyDown == KEY_F1 then -- вперед
		if Player[playerid].SS_cvob ~= nil then
		Player[playerid].nmodel = 1
		Player[playerid].Catalog = 1
		--UpdatePlayerDraw(playerid, EditorDraw6n1, 5800, 5800, "->ALL", "Font_Old_10_White_Hi.TGA", 255, 207, 64)
		--UpdatePlayerDraw(playerid, EditorDraw6n2, 6330, 5800, "MISC", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
		SS_period(playerid)
		   SS_NewVob(playerid)
		end
	elseif keyDown == KEY_F2 then -- вперед
		if Player[playerid].SS_cvob ~= nil then
		Player[playerid].nmodel = 1
		Player[playerid].Catalog = 2
		--UpdatePlayerDraw(playerid, EditorDraw6n1, 5800, 5800, "ALL", "Font_Old_10_White_Hi.TGA", 255, 255, 255)
		--UpdatePlayerDraw(playerid, EditorDraw6n2, 6330, 5800, "->MISC", "Font_Old_10_White_Hi.TGA", 255, 207, 64)
		SS_period(playerid)
		   SS_NewVob(playerid)
		end
	elseif keyDown == KEY_COMMA then -- уменьшить скорость
	if Player[playerid].SS_cvob ~= nil then
	    --Player[playerid].SS_ms = Player[playerid].SS_ms - 5;
		Player[playerid].SS_rs = Player[playerid].SS_rs - 3;
         SS_Speed(playerid)
		end
	elseif keyDown == KEY_PERIOD then -- увеличить скорость
	if Player[playerid].SS_cvob ~= nil then
	    --Player[playerid].SS_ms = Player[playerid].SS_ms + 5;
		Player[playerid].SS_rs = Player[playerid].SS_rs + 3;
         SS_Speed(playerid)
		end
	elseif keyDown == KEY_MINUS then -- уменьшить скорость
	if Player[playerid].SS_cvob ~= nil then
	    Player[playerid].SS_ms = Player[playerid].SS_ms - 3;
		--Player[playerid].SS_rs = Player[playerid].SS_rs - 5;
         SS_Speed(playerid)
		end
	elseif keyDown == KEY_EQUALS then -- увеличить скорость
	if Player[playerid].SS_cvob ~= nil then
	    Player[playerid].SS_ms = Player[playerid].SS_ms + 3;
		--Player[playerid].SS_rs = Player[playerid].SS_rs + 5;
         SS_Speed(playerid)
		end
	end
end

function yaya(playerid)
print("press")
end

function SS_period(playerid)
if Player[playerid].SS_cvob ~= nil then
		local x,y,z = VobIDs[Player[playerid].SS_cID]:GetPosition();
		Player[playerid].coord_x = x;
		Player[playerid].coord_y = y;
		Player[playerid].coord_z = z;
		local r_x,r_y,r_z = VobIDs[Player[playerid].SS_cID]:GetRotation();
		Player[playerid].coord_r_x = r_x;
		Player[playerid].coord_r_y = r_y;
		Player[playerid].coord_r_z = r_z;
		--local r_x, r_y, r_z = VobIDs[_f]:GetRotation() Player[playerid].coord_r_x = nil;
	if Player[playerid].SS_cvob ~= nil then
		VobIDs[Player[playerid].SS_cID]:Destroy();
		if Player[playerid].SS_cID ~= #VobIDs then
			for i = Player[playerid].SS_cID+1, #VobIDs do 
				VobIDs[i-1] = VobIDs[i];
				VobModels[i-1] = VobModels[i];
			end
			--VobIDs[Player[playerid].SS_cID] = nil;
			--VobModels[Player[playerid].SS_cID] = nil;
		else
			VobIDs[Player[playerid].SS_cID] = nil;
		end
    end
end
end

function SS_one(playerid)
		local r_x = Player[playerid].coord_r_x;
		local r_y = Player[playerid].coord_r_y;
		local r_z = Player[playerid].coord_r_z;
        local _x = Player[playerid].coord_x;
		local _y = Player[playerid].coord_y;
		local _z = Player[playerid].coord_z;
        --local _x, _y, _z = GetPlayerPos(playerid);
		local _n = #VobIDs;
		--Objectlist[Editor[playerid].nmodel
		if Player[playerid].Catalog == 1 then
		if Player[playerid].nmodel ~= 1 then
		Player[playerid].nmodel = Player[playerid].nmodel-1
		else
		Player[playerid].nmodel = 945
		end
		elseif Player[playerid].Catalog == 2 then
		if Player[playerid].nmodel ~= 1 then
		Player[playerid].nmodel = Player[playerid].nmodel-1
		else
		Player[playerid].nmodel = 408
		end
		end
		--tempvar = fileRead:read("*l");
		if Player[playerid].Catalog == 1 then
		VobIDs[(_n+1)] = Vob.Create(Objectlist[Player[playerid].nmodel], GetPlayerWorld(playerid), _x, _y, _z);
		VobIDs[(_n+1)]:SetRotation(r_x, r_y, r_z)
		VobModels[(_n+1)] = string.upper(Objectlist[Player[playerid].nmodel]);
		elseif Player[playerid].Catalog == 2 then
		VobIDs[(_n+1)] = Vob.Create(ObjectlistLn[Player[playerid].nmodel], GetPlayerWorld(playerid), _x, _y, _z);
		VobIDs[(_n+1)]:SetRotation(r_x, r_y, r_z)
		VobModels[(_n+1)] = string.upper(ObjectlistLn[Player[playerid].nmodel]);
		end
		SS_Give_Control(playerid, VobIDs[(_n+1)], _n+1);
		Player[playerid].SS_cID = _n + 1;
end

function SS_two(playerid)
        local r_x = Player[playerid].coord_r_x;
		local r_y = Player[playerid].coord_r_y;
		local r_z = Player[playerid].coord_r_z;
        local _x = Player[playerid].coord_x;
		local _y = Player[playerid].coord_y;
		local _z = Player[playerid].coord_z;
        --local _x, _y, _z = GetPlayerPos(playerid);
		local _n = #VobIDs;
		--Objectlist[Editor[playerid].nmodel
		if Player[playerid].Catalog == 1 then
		if Player[playerid].nmodel ~= 945 then
		Player[playerid].nmodel = Player[playerid].nmodel+1
		else
		Player[playerid].nmodel = 1
		end
		elseif Player[playerid].Catalog == 2 then
		if Player[playerid].nmodel ~= 408 then
		Player[playerid].nmodel = Player[playerid].nmodel+1
		else
		Player[playerid].nmodel = 1
		end
		end
		--tempvar = fileRead:read("*l");
		if Player[playerid].Catalog == 1 then
		VobIDs[(_n+1)] = Vob.Create(Objectlist[Player[playerid].nmodel], GetPlayerWorld(playerid), _x, _y, _z);
		VobIDs[(_n+1)]:SetRotation(r_x, r_y, r_z)
		VobModels[(_n+1)] = string.upper(Objectlist[Player[playerid].nmodel]);
		elseif Player[playerid].Catalog == 2 then
		VobIDs[(_n+1)] = Vob.Create(ObjectlistLn[Player[playerid].nmodel], GetPlayerWorld(playerid), _x, _y, _z);
		VobIDs[(_n+1)]:SetRotation(r_x, r_y, r_z)
		VobModels[(_n+1)] = string.upper(ObjectlistLn[Player[playerid].nmodel]);
		end
		SS_Give_Control(playerid, VobIDs[(_n+1)], _n+1);
		Player[playerid].SS_cID = _n + 1;
end

function OnPlayerDisconnect(playerid, p_classid, killerid, k_classid)
	if Player[playerid].SS_already == true then
		SS_Reset_Params(playerid);
	end
end

function OnPlayerConnect(playerid)
	if IsNPC(playerid) == 0 then
		print("adasd")
		Player[playerid].SS = false;
	end
end

print("--================================--")
print("*    SlashSlash has benn loaded    *")
print("--================================--")